/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApplicationProcessNamingInfoMessage.proto

package rina.object.gpb;

public final class ApplicationProcessNamingInfoMessage_t {
  private ApplicationProcessNamingInfoMessage_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface applicationProcessNamingInfo_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string applicationProcessName = 1;
    boolean hasApplicationProcessName();
    String getApplicationProcessName();
    
    // optional string applicationProcessInstance = 2;
    boolean hasApplicationProcessInstance();
    String getApplicationProcessInstance();
    
    // optional string applicationEntityName = 3;
    boolean hasApplicationEntityName();
    String getApplicationEntityName();
    
    // optional string applicationEntityInstance = 4;
    boolean hasApplicationEntityInstance();
    String getApplicationEntityInstance();
  }
  public static final class applicationProcessNamingInfo_t extends
      com.google.protobuf.GeneratedMessage
      implements applicationProcessNamingInfo_tOrBuilder {
    // Use applicationProcessNamingInfo_t.newBuilder() to construct.
    private applicationProcessNamingInfo_t(Builder builder) {
      super(builder);
    }
    private applicationProcessNamingInfo_t(boolean noInit) {}
    
    private static final applicationProcessNamingInfo_t defaultInstance;
    public static applicationProcessNamingInfo_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public applicationProcessNamingInfo_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.internal_static_rina_messages_applicationProcessNamingInfo_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.internal_static_rina_messages_applicationProcessNamingInfo_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string applicationProcessName = 1;
    public static final int APPLICATIONPROCESSNAME_FIELD_NUMBER = 1;
    private java.lang.Object applicationProcessName_;
    public boolean hasApplicationProcessName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getApplicationProcessName() {
      java.lang.Object ref = applicationProcessName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationProcessName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationProcessNameBytes() {
      java.lang.Object ref = applicationProcessName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationProcessName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string applicationProcessInstance = 2;
    public static final int APPLICATIONPROCESSINSTANCE_FIELD_NUMBER = 2;
    private java.lang.Object applicationProcessInstance_;
    public boolean hasApplicationProcessInstance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getApplicationProcessInstance() {
      java.lang.Object ref = applicationProcessInstance_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationProcessInstance_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationProcessInstanceBytes() {
      java.lang.Object ref = applicationProcessInstance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationProcessInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string applicationEntityName = 3;
    public static final int APPLICATIONENTITYNAME_FIELD_NUMBER = 3;
    private java.lang.Object applicationEntityName_;
    public boolean hasApplicationEntityName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getApplicationEntityName() {
      java.lang.Object ref = applicationEntityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationEntityName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationEntityNameBytes() {
      java.lang.Object ref = applicationEntityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationEntityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string applicationEntityInstance = 4;
    public static final int APPLICATIONENTITYINSTANCE_FIELD_NUMBER = 4;
    private java.lang.Object applicationEntityInstance_;
    public boolean hasApplicationEntityInstance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getApplicationEntityInstance() {
      java.lang.Object ref = applicationEntityInstance_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationEntityInstance_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationEntityInstanceBytes() {
      java.lang.Object ref = applicationEntityInstance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationEntityInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      applicationProcessName_ = "";
      applicationProcessInstance_ = "";
      applicationEntityName_ = "";
      applicationEntityInstance_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasApplicationProcessName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getApplicationProcessNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getApplicationProcessInstanceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getApplicationEntityNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getApplicationEntityInstanceBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getApplicationProcessNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getApplicationProcessInstanceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getApplicationEntityNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getApplicationEntityInstanceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.internal_static_rina_messages_applicationProcessNamingInfo_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.internal_static_rina_messages_applicationProcessNamingInfo_t_fieldAccessorTable;
      }
      
      // Construct using rina.messages.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        applicationProcessName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationProcessInstance_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        applicationEntityName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        applicationEntityInstance_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDescriptor();
      }
      
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getDefaultInstanceForType() {
        return rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      }
      
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t build() {
        rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t buildPartial() {
        rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t result = new rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.applicationProcessName_ = applicationProcessName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.applicationProcessInstance_ = applicationProcessInstance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.applicationEntityName_ = applicationEntityName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.applicationEntityInstance_ = applicationEntityInstance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t) {
          return mergeFrom((rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t other) {
        if (other == rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance()) return this;
        if (other.hasApplicationProcessName()) {
          setApplicationProcessName(other.getApplicationProcessName());
        }
        if (other.hasApplicationProcessInstance()) {
          setApplicationProcessInstance(other.getApplicationProcessInstance());
        }
        if (other.hasApplicationEntityName()) {
          setApplicationEntityName(other.getApplicationEntityName());
        }
        if (other.hasApplicationEntityInstance()) {
          setApplicationEntityInstance(other.getApplicationEntityInstance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasApplicationProcessName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              applicationProcessName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              applicationProcessInstance_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              applicationEntityName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              applicationEntityInstance_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string applicationProcessName = 1;
      private java.lang.Object applicationProcessName_ = "";
      public boolean hasApplicationProcessName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getApplicationProcessName() {
        java.lang.Object ref = applicationProcessName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationProcessName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationProcessName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        applicationProcessName_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationProcessName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationProcessName_ = getDefaultInstance().getApplicationProcessName();
        onChanged();
        return this;
      }
      void setApplicationProcessName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        applicationProcessName_ = value;
        onChanged();
      }
      
      // optional string applicationProcessInstance = 2;
      private java.lang.Object applicationProcessInstance_ = "";
      public boolean hasApplicationProcessInstance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getApplicationProcessInstance() {
        java.lang.Object ref = applicationProcessInstance_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationProcessInstance_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationProcessInstance(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        applicationProcessInstance_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationProcessInstance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        applicationProcessInstance_ = getDefaultInstance().getApplicationProcessInstance();
        onChanged();
        return this;
      }
      void setApplicationProcessInstance(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        applicationProcessInstance_ = value;
        onChanged();
      }
      
      // optional string applicationEntityName = 3;
      private java.lang.Object applicationEntityName_ = "";
      public boolean hasApplicationEntityName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getApplicationEntityName() {
        java.lang.Object ref = applicationEntityName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationEntityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationEntityName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        applicationEntityName_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationEntityName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        applicationEntityName_ = getDefaultInstance().getApplicationEntityName();
        onChanged();
        return this;
      }
      void setApplicationEntityName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        applicationEntityName_ = value;
        onChanged();
      }
      
      // optional string applicationEntityInstance = 4;
      private java.lang.Object applicationEntityInstance_ = "";
      public boolean hasApplicationEntityInstance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getApplicationEntityInstance() {
        java.lang.Object ref = applicationEntityInstance_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationEntityInstance_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationEntityInstance(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        applicationEntityInstance_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationEntityInstance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        applicationEntityInstance_ = getDefaultInstance().getApplicationEntityInstance();
        onChanged();
        return this;
      }
      void setApplicationEntityInstance(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        applicationEntityInstance_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.applicationProcessNamingInfo_t)
    }
    
    static {
      defaultInstance = new applicationProcessNamingInfo_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.applicationProcessNamingInfo_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_applicationProcessNamingInfo_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_applicationProcessNamingInfo_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)ApplicationProcessNamingInfoMessage.pr" +
      "oto\022\rrina.messages\"\246\001\n\036applicationProces" +
      "sNamingInfo_t\022\036\n\026applicationProcessName\030" +
      "\001 \002(\t\022\"\n\032applicationProcessInstance\030\002 \001(" +
      "\t\022\035\n\025applicationEntityName\030\003 \001(\t\022!\n\031appl" +
      "icationEntityInstance\030\004 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_applicationProcessNamingInfo_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_applicationProcessNamingInfo_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_applicationProcessNamingInfo_t_descriptor,
              new java.lang.String[] { "ApplicationProcessName", "ApplicationProcessInstance", "ApplicationEntityName", "ApplicationEntityInstance", },
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.class,
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
