/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directoryForwardingTableEntry.proto

package rina.object.gpb;

public final class DirectoryForwardingTableEntry_t {
  private DirectoryForwardingTableEntry_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface directoryForwardingTableEntrySet_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rina.object.gpb.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
    java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> 
        getDirectoryForwardingTableEntryList();
    rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t getDirectoryForwardingTableEntry(int index);
    int getDirectoryForwardingTableEntryCount();
    java.util.List<? extends rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder> 
        getDirectoryForwardingTableEntryOrBuilderList();
    rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder getDirectoryForwardingTableEntryOrBuilder(
        int index);
  }
  public static final class directoryForwardingTableEntrySet_t extends
      com.google.protobuf.GeneratedMessage
      implements directoryForwardingTableEntrySet_tOrBuilder {
    // Use directoryForwardingTableEntrySet_t.newBuilder() to construct.
    private directoryForwardingTableEntrySet_t(Builder builder) {
      super(builder);
    }
    private directoryForwardingTableEntrySet_t(boolean noInit) {}
    
    private static final directoryForwardingTableEntrySet_t defaultInstance;
    public static directoryForwardingTableEntrySet_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public directoryForwardingTableEntrySet_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_fieldAccessorTable;
    }
    
    // repeated .rina.object.gpb.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
    public static final int DIRECTORYFORWARDINGTABLEENTRY_FIELD_NUMBER = 1;
    private java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> directoryForwardingTableEntry_;
    public java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> getDirectoryForwardingTableEntryList() {
      return directoryForwardingTableEntry_;
    }
    public java.util.List<? extends rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder> 
        getDirectoryForwardingTableEntryOrBuilderList() {
      return directoryForwardingTableEntry_;
    }
    public int getDirectoryForwardingTableEntryCount() {
      return directoryForwardingTableEntry_.size();
    }
    public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t getDirectoryForwardingTableEntry(int index) {
      return directoryForwardingTableEntry_.get(index);
    }
    public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder getDirectoryForwardingTableEntryOrBuilder(
        int index) {
      return directoryForwardingTableEntry_.get(index);
    }
    
    private void initFields() {
      directoryForwardingTableEntry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getDirectoryForwardingTableEntryCount(); i++) {
        if (!getDirectoryForwardingTableEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < directoryForwardingTableEntry_.size(); i++) {
        output.writeMessage(1, directoryForwardingTableEntry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < directoryForwardingTableEntry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, directoryForwardingTableEntry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.DirectoryForwardingTableEntry.directoryForwardingTableEntrySet_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDirectoryForwardingTableEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (directoryForwardingTableEntryBuilder_ == null) {
          directoryForwardingTableEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          directoryForwardingTableEntryBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t.getDescriptor();
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t getDefaultInstanceForType() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t.getDefaultInstance();
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t build() {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t buildPartial() {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t result = new rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t(this);
        int from_bitField0_ = bitField0_;
        if (directoryForwardingTableEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            directoryForwardingTableEntry_ = java.util.Collections.unmodifiableList(directoryForwardingTableEntry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.directoryForwardingTableEntry_ = directoryForwardingTableEntry_;
        } else {
          result.directoryForwardingTableEntry_ = directoryForwardingTableEntryBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t) {
          return mergeFrom((rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t other) {
        if (other == rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t.getDefaultInstance()) return this;
        if (directoryForwardingTableEntryBuilder_ == null) {
          if (!other.directoryForwardingTableEntry_.isEmpty()) {
            if (directoryForwardingTableEntry_.isEmpty()) {
              directoryForwardingTableEntry_ = other.directoryForwardingTableEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDirectoryForwardingTableEntryIsMutable();
              directoryForwardingTableEntry_.addAll(other.directoryForwardingTableEntry_);
            }
            onChanged();
          }
        } else {
          if (!other.directoryForwardingTableEntry_.isEmpty()) {
            if (directoryForwardingTableEntryBuilder_.isEmpty()) {
              directoryForwardingTableEntryBuilder_.dispose();
              directoryForwardingTableEntryBuilder_ = null;
              directoryForwardingTableEntry_ = other.directoryForwardingTableEntry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              directoryForwardingTableEntryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDirectoryForwardingTableEntryFieldBuilder() : null;
            } else {
              directoryForwardingTableEntryBuilder_.addAllMessages(other.directoryForwardingTableEntry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getDirectoryForwardingTableEntryCount(); i++) {
          if (!getDirectoryForwardingTableEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder subBuilder = rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDirectoryForwardingTableEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rina.object.gpb.directoryForwardingTableEntry_t directoryForwardingTableEntry = 1;
      private java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> directoryForwardingTableEntry_ =
        java.util.Collections.emptyList();
      private void ensureDirectoryForwardingTableEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          directoryForwardingTableEntry_ = new java.util.ArrayList<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t>(directoryForwardingTableEntry_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder> directoryForwardingTableEntryBuilder_;
      
      public java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> getDirectoryForwardingTableEntryList() {
        if (directoryForwardingTableEntryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(directoryForwardingTableEntry_);
        } else {
          return directoryForwardingTableEntryBuilder_.getMessageList();
        }
      }
      public int getDirectoryForwardingTableEntryCount() {
        if (directoryForwardingTableEntryBuilder_ == null) {
          return directoryForwardingTableEntry_.size();
        } else {
          return directoryForwardingTableEntryBuilder_.getCount();
        }
      }
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t getDirectoryForwardingTableEntry(int index) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          return directoryForwardingTableEntry_.get(index);
        } else {
          return directoryForwardingTableEntryBuilder_.getMessage(index);
        }
      }
      public Builder setDirectoryForwardingTableEntry(
          int index, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t value) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.set(index, value);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDirectoryForwardingTableEntry(
          int index, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder builderForValue) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.set(index, builderForValue.build());
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t value) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.add(value);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(
          int index, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t value) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.add(index, value);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(
          rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder builderForValue) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.add(builderForValue.build());
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDirectoryForwardingTableEntry(
          int index, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder builderForValue) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.add(index, builderForValue.build());
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDirectoryForwardingTableEntry(
          java.lang.Iterable<? extends rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t> values) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          ensureDirectoryForwardingTableEntryIsMutable();
          super.addAll(values, directoryForwardingTableEntry_);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDirectoryForwardingTableEntry() {
        if (directoryForwardingTableEntryBuilder_ == null) {
          directoryForwardingTableEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.clear();
        }
        return this;
      }
      public Builder removeDirectoryForwardingTableEntry(int index) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          ensureDirectoryForwardingTableEntryIsMutable();
          directoryForwardingTableEntry_.remove(index);
          onChanged();
        } else {
          directoryForwardingTableEntryBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder getDirectoryForwardingTableEntryBuilder(
          int index) {
        return getDirectoryForwardingTableEntryFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder getDirectoryForwardingTableEntryOrBuilder(
          int index) {
        if (directoryForwardingTableEntryBuilder_ == null) {
          return directoryForwardingTableEntry_.get(index);  } else {
          return directoryForwardingTableEntryBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder> 
           getDirectoryForwardingTableEntryOrBuilderList() {
        if (directoryForwardingTableEntryBuilder_ != null) {
          return directoryForwardingTableEntryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(directoryForwardingTableEntry_);
        }
      }
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder addDirectoryForwardingTableEntryBuilder() {
        return getDirectoryForwardingTableEntryFieldBuilder().addBuilder(
            rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.getDefaultInstance());
      }
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder addDirectoryForwardingTableEntryBuilder(
          int index) {
        return getDirectoryForwardingTableEntryFieldBuilder().addBuilder(
            index, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder> 
           getDirectoryForwardingTableEntryBuilderList() {
        return getDirectoryForwardingTableEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder> 
          getDirectoryForwardingTableEntryFieldBuilder() {
        if (directoryForwardingTableEntryBuilder_ == null) {
          directoryForwardingTableEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder, rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder>(
                  directoryForwardingTableEntry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          directoryForwardingTableEntry_ = null;
        }
        return directoryForwardingTableEntryBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.directoryForwardingTableEntrySet_t)
    }
    
    static {
      defaultInstance = new directoryForwardingTableEntrySet_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.directoryForwardingTableEntrySet_t)
  }
  
  public interface directoryForwardingTableEntry_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rina.object.gpb.applicationProcessNamingInfo_t applicationName = 1;
    boolean hasApplicationName();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationName();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameOrBuilder();
    
    // required uint64 ipcProcessAddress = 2;
    boolean hasIpcProcessAddress();
    long getIpcProcessAddress();
    
    // optional uint64 timestamp = 3;
    boolean hasTimestamp();
    long getTimestamp();
  }
  public static final class directoryForwardingTableEntry_t extends
      com.google.protobuf.GeneratedMessage
      implements directoryForwardingTableEntry_tOrBuilder {
    // Use directoryForwardingTableEntry_t.newBuilder() to construct.
    private directoryForwardingTableEntry_t(Builder builder) {
      super(builder);
    }
    private directoryForwardingTableEntry_t(boolean noInit) {}
    
    private static final directoryForwardingTableEntry_t defaultInstance;
    public static directoryForwardingTableEntry_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public directoryForwardingTableEntry_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntry_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntry_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .rina.object.gpb.applicationProcessNamingInfo_t applicationName = 1;
    public static final int APPLICATIONNAME_FIELD_NUMBER = 1;
    private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t applicationName_;
    public boolean hasApplicationName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationName() {
      return applicationName_;
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameOrBuilder() {
      return applicationName_;
    }
    
    // required uint64 ipcProcessAddress = 2;
    public static final int IPCPROCESSADDRESS_FIELD_NUMBER = 2;
    private long ipcProcessAddress_;
    public boolean hasIpcProcessAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getIpcProcessAddress() {
      return ipcProcessAddress_;
    }
    
    // optional uint64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      applicationName_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      ipcProcessAddress_ = 0L;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasApplicationName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpcProcessAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getApplicationName().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, applicationName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, ipcProcessAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, applicationName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, ipcProcessAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntry_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.internal_static_rina_object_gpb_directoryForwardingTableEntry_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.DirectoryForwardingTableEntry.directoryForwardingTableEntry_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getApplicationNameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (applicationNameBuilder_ == null) {
          applicationName_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
        } else {
          applicationNameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        ipcProcessAddress_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.getDescriptor();
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t getDefaultInstanceForType() {
        return rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.getDefaultInstance();
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t build() {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t buildPartial() {
        rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t result = new rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (applicationNameBuilder_ == null) {
          result.applicationName_ = applicationName_;
        } else {
          result.applicationName_ = applicationNameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ipcProcessAddress_ = ipcProcessAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t) {
          return mergeFrom((rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t other) {
        if (other == rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.getDefaultInstance()) return this;
        if (other.hasApplicationName()) {
          mergeApplicationName(other.getApplicationName());
        }
        if (other.hasIpcProcessAddress()) {
          setIpcProcessAddress(other.getIpcProcessAddress());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasApplicationName()) {
          
          return false;
        }
        if (!hasIpcProcessAddress()) {
          
          return false;
        }
        if (!getApplicationName().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder subBuilder = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder();
              if (hasApplicationName()) {
                subBuilder.mergeFrom(getApplicationName());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setApplicationName(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ipcProcessAddress_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rina.object.gpb.applicationProcessNamingInfo_t applicationName = 1;
      private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t applicationName_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> applicationNameBuilder_;
      public boolean hasApplicationName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationName() {
        if (applicationNameBuilder_ == null) {
          return applicationName_;
        } else {
          return applicationNameBuilder_.getMessage();
        }
      }
      public Builder setApplicationName(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (applicationNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationName_ = value;
          onChanged();
        } else {
          applicationNameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setApplicationName(
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (applicationNameBuilder_ == null) {
          applicationName_ = builderForValue.build();
          onChanged();
        } else {
          applicationNameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeApplicationName(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (applicationNameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              applicationName_ != rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance()) {
            applicationName_ =
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder(applicationName_).mergeFrom(value).buildPartial();
          } else {
            applicationName_ = value;
          }
          onChanged();
        } else {
          applicationNameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearApplicationName() {
        if (applicationNameBuilder_ == null) {
          applicationName_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
          onChanged();
        } else {
          applicationNameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder getApplicationNameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getApplicationNameFieldBuilder().getBuilder();
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameOrBuilder() {
        if (applicationNameBuilder_ != null) {
          return applicationNameBuilder_.getMessageOrBuilder();
        } else {
          return applicationName_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
          getApplicationNameFieldBuilder() {
        if (applicationNameBuilder_ == null) {
          applicationNameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder>(
                  applicationName_,
                  getParentForChildren(),
                  isClean());
          applicationName_ = null;
        }
        return applicationNameBuilder_;
      }
      
      // required uint64 ipcProcessAddress = 2;
      private long ipcProcessAddress_ ;
      public boolean hasIpcProcessAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getIpcProcessAddress() {
        return ipcProcessAddress_;
      }
      public Builder setIpcProcessAddress(long value) {
        bitField0_ |= 0x00000002;
        ipcProcessAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearIpcProcessAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ipcProcessAddress_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 timestamp = 3;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.directoryForwardingTableEntry_t)
    }
    
    static {
      defaultInstance = new directoryForwardingTableEntry_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.directoryForwardingTableEntry_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_directoryForwardingTableEntry_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_directoryForwardingTableEntry_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#directoryForwardingTableEntry.proto\022\017r" +
      "ina.object.gpb\032)ApplicationProcessNaming" +
      "InfoMessage.proto\"}\n\"directoryForwarding" +
      "TableEntrySet_t\022W\n\035directoryForwardingTa" +
      "bleEntry\030\001 \003(\01320.rina.object.gpb.directo" +
      "ryForwardingTableEntry_t\"\231\001\n\037directoryFo" +
      "rwardingTableEntry_t\022H\n\017applicationName\030" +
      "\001 \002(\0132/.rina.object.gpb.applicationProce" +
      "ssNamingInfo_t\022\031\n\021ipcProcessAddress\030\002 \002(" +
      "\004\022\021\n\ttimestamp\030\003 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_directoryForwardingTableEntrySet_t_descriptor,
              new java.lang.String[] { "DirectoryForwardingTableEntry", },
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t.class,
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntrySet_t.Builder.class);
          internal_static_rina_object_gpb_directoryForwardingTableEntry_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_object_gpb_directoryForwardingTableEntry_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_directoryForwardingTableEntry_t_descriptor,
              new java.lang.String[] { "ApplicationName", "IpcProcessAddress", "Timestamp", },
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.class,
              rina.object.gpb.DirectoryForwardingTableEntry_t.directoryForwardingTableEntry_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
