/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IDDMessage_t

package rina.object.gpb;

public final class IDDMessage_t {
  private IDDMessage_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum opCode_t
      implements com.google.protobuf.ProtocolMessageEnum {
    Request(0, 0),
    Response(1, 1),
    Register(2, 2),
    ;
    
    public static final int Request_VALUE = 0;
    public static final int Response_VALUE = 1;
    public static final int Register_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static opCode_t valueOf(int value) {
      switch (value) {
        case 0: return Request;
        case 1: return Response;
        case 2: return Register;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<opCode_t>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<opCode_t>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<opCode_t>() {
            public opCode_t findValueByNumber(int number) {
              return opCode_t.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return rina.object.gpb.IDDMessage_t.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final opCode_t[] VALUES = {
      Request, Response, Register, 
    };
    
    public static opCode_t valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private opCode_t(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:rina.object.gpb.opCode_t)
  }
  
  public interface iddResponse_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string difName = 1;
    boolean hasDifName();
    String getDifName();
    
    // optional .rina.object.gpb.applicationProcessNamingInfo_t ipcProcessNameInfo = 2;
    boolean hasIpcProcessNameInfo();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getIpcProcessNameInfo();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getIpcProcessNameInfoOrBuilder();
    
    // repeated string supportingDIFNames = 3;
    java.util.List<String> getSupportingDIFNamesList();
    int getSupportingDIFNamesCount();
    String getSupportingDIFNames(int index);
  }
  public static final class iddResponse_t extends
      com.google.protobuf.GeneratedMessage
      implements iddResponse_tOrBuilder {
    // Use iddResponse_t.newBuilder() to construct.
    private iddResponse_t(Builder builder) {
      super(builder);
    }
    private iddResponse_t(boolean noInit) {}
    
    private static final iddResponse_t defaultInstance;
    public static iddResponse_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public iddResponse_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddResponse_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddResponse_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string difName = 1;
    public static final int DIFNAME_FIELD_NUMBER = 1;
    private java.lang.Object difName_;
    public boolean hasDifName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDifName() {
      java.lang.Object ref = difName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          difName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDifNameBytes() {
      java.lang.Object ref = difName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        difName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .rina.object.gpb.applicationProcessNamingInfo_t ipcProcessNameInfo = 2;
    public static final int IPCPROCESSNAMEINFO_FIELD_NUMBER = 2;
    private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t ipcProcessNameInfo_;
    public boolean hasIpcProcessNameInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getIpcProcessNameInfo() {
      return ipcProcessNameInfo_;
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getIpcProcessNameInfoOrBuilder() {
      return ipcProcessNameInfo_;
    }
    
    // repeated string supportingDIFNames = 3;
    public static final int SUPPORTINGDIFNAMES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList supportingDIFNames_;
    public java.util.List<String>
        getSupportingDIFNamesList() {
      return supportingDIFNames_;
    }
    public int getSupportingDIFNamesCount() {
      return supportingDIFNames_.size();
    }
    public String getSupportingDIFNames(int index) {
      return supportingDIFNames_.get(index);
    }
    
    private void initFields() {
      difName_ = "";
      ipcProcessNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      supportingDIFNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasIpcProcessNameInfo()) {
        if (!getIpcProcessNameInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDifNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, ipcProcessNameInfo_);
      }
      for (int i = 0; i < supportingDIFNames_.size(); i++) {
        output.writeBytes(3, supportingDIFNames_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDifNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ipcProcessNameInfo_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < supportingDIFNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(supportingDIFNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSupportingDIFNamesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddResponse_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.IDDMessage_t.iddResponse_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddResponse_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddResponse_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.IDDMessageT.iddResponse_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIpcProcessNameInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        difName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (ipcProcessNameInfoBuilder_ == null) {
          ipcProcessNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
        } else {
          ipcProcessNameInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        supportingDIFNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.IDDMessage_t.iddResponse_t.getDescriptor();
      }
      
      public rina.object.gpb.IDDMessage_t.iddResponse_t getDefaultInstanceForType() {
        return rina.object.gpb.IDDMessage_t.iddResponse_t.getDefaultInstance();
      }
      
      public rina.object.gpb.IDDMessage_t.iddResponse_t build() {
        rina.object.gpb.IDDMessage_t.iddResponse_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.IDDMessage_t.iddResponse_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.IDDMessage_t.iddResponse_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.IDDMessage_t.iddResponse_t buildPartial() {
        rina.object.gpb.IDDMessage_t.iddResponse_t result = new rina.object.gpb.IDDMessage_t.iddResponse_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.difName_ = difName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (ipcProcessNameInfoBuilder_ == null) {
          result.ipcProcessNameInfo_ = ipcProcessNameInfo_;
        } else {
          result.ipcProcessNameInfo_ = ipcProcessNameInfoBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          supportingDIFNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              supportingDIFNames_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.supportingDIFNames_ = supportingDIFNames_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.IDDMessage_t.iddResponse_t) {
          return mergeFrom((rina.object.gpb.IDDMessage_t.iddResponse_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.IDDMessage_t.iddResponse_t other) {
        if (other == rina.object.gpb.IDDMessage_t.iddResponse_t.getDefaultInstance()) return this;
        if (other.hasDifName()) {
          setDifName(other.getDifName());
        }
        if (other.hasIpcProcessNameInfo()) {
          mergeIpcProcessNameInfo(other.getIpcProcessNameInfo());
        }
        if (!other.supportingDIFNames_.isEmpty()) {
          if (supportingDIFNames_.isEmpty()) {
            supportingDIFNames_ = other.supportingDIFNames_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSupportingDIFNamesIsMutable();
            supportingDIFNames_.addAll(other.supportingDIFNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasIpcProcessNameInfo()) {
          if (!getIpcProcessNameInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              difName_ = input.readBytes();
              break;
            }
            case 18: {
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder subBuilder = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder();
              if (hasIpcProcessNameInfo()) {
                subBuilder.mergeFrom(getIpcProcessNameInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIpcProcessNameInfo(subBuilder.buildPartial());
              break;
            }
            case 26: {
              ensureSupportingDIFNamesIsMutable();
              supportingDIFNames_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string difName = 1;
      private java.lang.Object difName_ = "";
      public boolean hasDifName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDifName() {
        java.lang.Object ref = difName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          difName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDifName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        difName_ = value;
        onChanged();
        return this;
      }
      public Builder clearDifName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        difName_ = getDefaultInstance().getDifName();
        onChanged();
        return this;
      }
      void setDifName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        difName_ = value;
        onChanged();
      }
      
      // optional .rina.object.gpb.applicationProcessNamingInfo_t ipcProcessNameInfo = 2;
      private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t ipcProcessNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> ipcProcessNameInfoBuilder_;
      public boolean hasIpcProcessNameInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getIpcProcessNameInfo() {
        if (ipcProcessNameInfoBuilder_ == null) {
          return ipcProcessNameInfo_;
        } else {
          return ipcProcessNameInfoBuilder_.getMessage();
        }
      }
      public Builder setIpcProcessNameInfo(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (ipcProcessNameInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ipcProcessNameInfo_ = value;
          onChanged();
        } else {
          ipcProcessNameInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setIpcProcessNameInfo(
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (ipcProcessNameInfoBuilder_ == null) {
          ipcProcessNameInfo_ = builderForValue.build();
          onChanged();
        } else {
          ipcProcessNameInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeIpcProcessNameInfo(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (ipcProcessNameInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              ipcProcessNameInfo_ != rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance()) {
            ipcProcessNameInfo_ =
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder(ipcProcessNameInfo_).mergeFrom(value).buildPartial();
          } else {
            ipcProcessNameInfo_ = value;
          }
          onChanged();
        } else {
          ipcProcessNameInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearIpcProcessNameInfo() {
        if (ipcProcessNameInfoBuilder_ == null) {
          ipcProcessNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
          onChanged();
        } else {
          ipcProcessNameInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder getIpcProcessNameInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIpcProcessNameInfoFieldBuilder().getBuilder();
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getIpcProcessNameInfoOrBuilder() {
        if (ipcProcessNameInfoBuilder_ != null) {
          return ipcProcessNameInfoBuilder_.getMessageOrBuilder();
        } else {
          return ipcProcessNameInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
          getIpcProcessNameInfoFieldBuilder() {
        if (ipcProcessNameInfoBuilder_ == null) {
          ipcProcessNameInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder>(
                  ipcProcessNameInfo_,
                  getParentForChildren(),
                  isClean());
          ipcProcessNameInfo_ = null;
        }
        return ipcProcessNameInfoBuilder_;
      }
      
      // repeated string supportingDIFNames = 3;
      private com.google.protobuf.LazyStringList supportingDIFNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSupportingDIFNamesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          supportingDIFNames_ = new com.google.protobuf.LazyStringArrayList(supportingDIFNames_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getSupportingDIFNamesList() {
        return java.util.Collections.unmodifiableList(supportingDIFNames_);
      }
      public int getSupportingDIFNamesCount() {
        return supportingDIFNames_.size();
      }
      public String getSupportingDIFNames(int index) {
        return supportingDIFNames_.get(index);
      }
      public Builder setSupportingDIFNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSupportingDIFNamesIsMutable();
        supportingDIFNames_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addSupportingDIFNames(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSupportingDIFNamesIsMutable();
        supportingDIFNames_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllSupportingDIFNames(
          java.lang.Iterable<String> values) {
        ensureSupportingDIFNamesIsMutable();
        super.addAll(values, supportingDIFNames_);
        onChanged();
        return this;
      }
      public Builder clearSupportingDIFNames() {
        supportingDIFNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addSupportingDIFNames(com.google.protobuf.ByteString value) {
        ensureSupportingDIFNamesIsMutable();
        supportingDIFNames_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.iddResponse_t)
    }
    
    static {
      defaultInstance = new iddResponse_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.iddResponse_t)
  }
  
  public interface iddMessage_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rina.object.gpb.opCode_t opCode = 1;
    boolean hasOpCode();
    rina.object.gpb.IDDMessage_t.opCode_t getOpCode();
    
    // optional uint32 result = 2;
    boolean hasResult();
    int getResult();
    
    // optional .rina.object.gpb.applicationProcessNamingInfo_t applicationNameInfo = 3;
    boolean hasApplicationNameInfo();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationNameInfo();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameInfoOrBuilder();
    
    // optional uint32 hopCount = 4;
    boolean hasHopCount();
    int getHopCount();
    
    // optional uint64 timeStamp = 5;
    boolean hasTimeStamp();
    long getTimeStamp();
    
    // repeated .rina.object.gpb.iddResponse_t iddResponse = 6;
    java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t> 
        getIddResponseList();
    rina.object.gpb.IDDMessage_t.iddResponse_t getIddResponse(int index);
    int getIddResponseCount();
    java.util.List<? extends rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder> 
        getIddResponseOrBuilderList();
    rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder getIddResponseOrBuilder(
        int index);
    
    // optional string difName = 7;
    boolean hasDifName();
    String getDifName();
    
    // repeated .rina.object.gpb.applicationProcessNamingInfo_t authenticatorNameInfo = 8;
    java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> 
        getAuthenticatorNameInfoList();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getAuthenticatorNameInfo(int index);
    int getAuthenticatorNameInfoCount();
    java.util.List<? extends rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
        getAuthenticatorNameInfoOrBuilderList();
    rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getAuthenticatorNameInfoOrBuilder(
        int index);
  }
  public static final class iddMessage_t extends
      com.google.protobuf.GeneratedMessage
      implements iddMessage_tOrBuilder {
    // Use iddMessage_t.newBuilder() to construct.
    private iddMessage_t(Builder builder) {
      super(builder);
    }
    private iddMessage_t(boolean noInit) {}
    
    private static final iddMessage_t defaultInstance;
    public static iddMessage_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public iddMessage_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddMessage_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddMessage_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .rina.object.gpb.opCode_t opCode = 1;
    public static final int OPCODE_FIELD_NUMBER = 1;
    private rina.object.gpb.IDDMessage_t.opCode_t opCode_;
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rina.object.gpb.IDDMessage_t.opCode_t getOpCode() {
      return opCode_;
    }
    
    // optional uint32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getResult() {
      return result_;
    }
    
    // optional .rina.object.gpb.applicationProcessNamingInfo_t applicationNameInfo = 3;
    public static final int APPLICATIONNAMEINFO_FIELD_NUMBER = 3;
    private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t applicationNameInfo_;
    public boolean hasApplicationNameInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationNameInfo() {
      return applicationNameInfo_;
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameInfoOrBuilder() {
      return applicationNameInfo_;
    }
    
    // optional uint32 hopCount = 4;
    public static final int HOPCOUNT_FIELD_NUMBER = 4;
    private int hopCount_;
    public boolean hasHopCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHopCount() {
      return hopCount_;
    }
    
    // optional uint64 timeStamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getTimeStamp() {
      return timeStamp_;
    }
    
    // repeated .rina.object.gpb.iddResponse_t iddResponse = 6;
    public static final int IDDRESPONSE_FIELD_NUMBER = 6;
    private java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t> iddResponse_;
    public java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t> getIddResponseList() {
      return iddResponse_;
    }
    public java.util.List<? extends rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder> 
        getIddResponseOrBuilderList() {
      return iddResponse_;
    }
    public int getIddResponseCount() {
      return iddResponse_.size();
    }
    public rina.object.gpb.IDDMessage_t.iddResponse_t getIddResponse(int index) {
      return iddResponse_.get(index);
    }
    public rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder getIddResponseOrBuilder(
        int index) {
      return iddResponse_.get(index);
    }
    
    // optional string difName = 7;
    public static final int DIFNAME_FIELD_NUMBER = 7;
    private java.lang.Object difName_;
    public boolean hasDifName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDifName() {
      java.lang.Object ref = difName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          difName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDifNameBytes() {
      java.lang.Object ref = difName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        difName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .rina.object.gpb.applicationProcessNamingInfo_t authenticatorNameInfo = 8;
    public static final int AUTHENTICATORNAMEINFO_FIELD_NUMBER = 8;
    private java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> authenticatorNameInfo_;
    public java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> getAuthenticatorNameInfoList() {
      return authenticatorNameInfo_;
    }
    public java.util.List<? extends rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
        getAuthenticatorNameInfoOrBuilderList() {
      return authenticatorNameInfo_;
    }
    public int getAuthenticatorNameInfoCount() {
      return authenticatorNameInfo_.size();
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getAuthenticatorNameInfo(int index) {
      return authenticatorNameInfo_.get(index);
    }
    public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getAuthenticatorNameInfoOrBuilder(
        int index) {
      return authenticatorNameInfo_.get(index);
    }
    
    private void initFields() {
      opCode_ = rina.object.gpb.IDDMessage_t.opCode_t.Request;
      result_ = 0;
      applicationNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      hopCount_ = 0;
      timeStamp_ = 0L;
      iddResponse_ = java.util.Collections.emptyList();
      difName_ = "";
      authenticatorNameInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasApplicationNameInfo()) {
        if (!getApplicationNameInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getIddResponseCount(); i++) {
        if (!getIddResponse(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getAuthenticatorNameInfoCount(); i++) {
        if (!getAuthenticatorNameInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, opCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, applicationNameInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, hopCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, timeStamp_);
      }
      for (int i = 0; i < iddResponse_.size(); i++) {
        output.writeMessage(6, iddResponse_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getDifNameBytes());
      }
      for (int i = 0; i < authenticatorNameInfo_.size(); i++) {
        output.writeMessage(8, authenticatorNameInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, applicationNameInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, hopCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, timeStamp_);
      }
      for (int i = 0; i < iddResponse_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, iddResponse_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDifNameBytes());
      }
      for (int i = 0; i < authenticatorNameInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, authenticatorNameInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.IDDMessage_t.iddMessage_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.IDDMessage_t.iddMessage_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.IDDMessage_t.iddMessage_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddMessage_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.IDDMessage_t.internal_static_rina_object_gpb_iddMessage_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.IDDMessageT.iddMessage_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getApplicationNameInfoFieldBuilder();
          getIddResponseFieldBuilder();
          getAuthenticatorNameInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        opCode_ = rina.object.gpb.IDDMessage_t.opCode_t.Request;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (applicationNameInfoBuilder_ == null) {
          applicationNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
        } else {
          applicationNameInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        hopCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (iddResponseBuilder_ == null) {
          iddResponse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          iddResponseBuilder_.clear();
        }
        difName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (authenticatorNameInfoBuilder_ == null) {
          authenticatorNameInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          authenticatorNameInfoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.IDDMessage_t.iddMessage_t.getDescriptor();
      }
      
      public rina.object.gpb.IDDMessage_t.iddMessage_t getDefaultInstanceForType() {
        return rina.object.gpb.IDDMessage_t.iddMessage_t.getDefaultInstance();
      }
      
      public rina.object.gpb.IDDMessage_t.iddMessage_t build() {
        rina.object.gpb.IDDMessage_t.iddMessage_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.IDDMessage_t.iddMessage_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.IDDMessage_t.iddMessage_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.IDDMessage_t.iddMessage_t buildPartial() {
        rina.object.gpb.IDDMessage_t.iddMessage_t result = new rina.object.gpb.IDDMessage_t.iddMessage_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opCode_ = opCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (applicationNameInfoBuilder_ == null) {
          result.applicationNameInfo_ = applicationNameInfo_;
        } else {
          result.applicationNameInfo_ = applicationNameInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hopCount_ = hopCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeStamp_ = timeStamp_;
        if (iddResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            iddResponse_ = java.util.Collections.unmodifiableList(iddResponse_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.iddResponse_ = iddResponse_;
        } else {
          result.iddResponse_ = iddResponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.difName_ = difName_;
        if (authenticatorNameInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            authenticatorNameInfo_ = java.util.Collections.unmodifiableList(authenticatorNameInfo_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.authenticatorNameInfo_ = authenticatorNameInfo_;
        } else {
          result.authenticatorNameInfo_ = authenticatorNameInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.IDDMessage_t.iddMessage_t) {
          return mergeFrom((rina.object.gpb.IDDMessage_t.iddMessage_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.IDDMessage_t.iddMessage_t other) {
        if (other == rina.object.gpb.IDDMessage_t.iddMessage_t.getDefaultInstance()) return this;
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasApplicationNameInfo()) {
          mergeApplicationNameInfo(other.getApplicationNameInfo());
        }
        if (other.hasHopCount()) {
          setHopCount(other.getHopCount());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (iddResponseBuilder_ == null) {
          if (!other.iddResponse_.isEmpty()) {
            if (iddResponse_.isEmpty()) {
              iddResponse_ = other.iddResponse_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureIddResponseIsMutable();
              iddResponse_.addAll(other.iddResponse_);
            }
            onChanged();
          }
        } else {
          if (!other.iddResponse_.isEmpty()) {
            if (iddResponseBuilder_.isEmpty()) {
              iddResponseBuilder_.dispose();
              iddResponseBuilder_ = null;
              iddResponse_ = other.iddResponse_;
              bitField0_ = (bitField0_ & ~0x00000020);
              iddResponseBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIddResponseFieldBuilder() : null;
            } else {
              iddResponseBuilder_.addAllMessages(other.iddResponse_);
            }
          }
        }
        if (other.hasDifName()) {
          setDifName(other.getDifName());
        }
        if (authenticatorNameInfoBuilder_ == null) {
          if (!other.authenticatorNameInfo_.isEmpty()) {
            if (authenticatorNameInfo_.isEmpty()) {
              authenticatorNameInfo_ = other.authenticatorNameInfo_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureAuthenticatorNameInfoIsMutable();
              authenticatorNameInfo_.addAll(other.authenticatorNameInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.authenticatorNameInfo_.isEmpty()) {
            if (authenticatorNameInfoBuilder_.isEmpty()) {
              authenticatorNameInfoBuilder_.dispose();
              authenticatorNameInfoBuilder_ = null;
              authenticatorNameInfo_ = other.authenticatorNameInfo_;
              bitField0_ = (bitField0_ & ~0x00000080);
              authenticatorNameInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAuthenticatorNameInfoFieldBuilder() : null;
            } else {
              authenticatorNameInfoBuilder_.addAllMessages(other.authenticatorNameInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOpCode()) {
          
          return false;
        }
        if (hasApplicationNameInfo()) {
          if (!getApplicationNameInfo().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getIddResponseCount(); i++) {
          if (!getIddResponse(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getAuthenticatorNameInfoCount(); i++) {
          if (!getAuthenticatorNameInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              rina.object.gpb.IDDMessage_t.opCode_t value = rina.object.gpb.IDDMessage_t.opCode_t.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                opCode_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              result_ = input.readUInt32();
              break;
            }
            case 26: {
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder subBuilder = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder();
              if (hasApplicationNameInfo()) {
                subBuilder.mergeFrom(getApplicationNameInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setApplicationNameInfo(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hopCount_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeStamp_ = input.readUInt64();
              break;
            }
            case 50: {
              rina.object.gpb.IDDMessage_t.iddResponse_t.Builder subBuilder = rina.object.gpb.IDDMessage_t.iddResponse_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIddResponse(subBuilder.buildPartial());
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              difName_ = input.readBytes();
              break;
            }
            case 66: {
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder subBuilder = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAuthenticatorNameInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rina.object.gpb.opCode_t opCode = 1;
      private rina.object.gpb.IDDMessage_t.opCode_t opCode_ = rina.object.gpb.IDDMessage_t.opCode_t.Request;
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rina.object.gpb.IDDMessage_t.opCode_t getOpCode() {
        return opCode_;
      }
      public Builder setOpCode(rina.object.gpb.IDDMessage_t.opCode_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        opCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opCode_ = rina.object.gpb.IDDMessage_t.opCode_t.Request;
        onChanged();
        return this;
      }
      
      // optional uint32 result = 2;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // optional .rina.object.gpb.applicationProcessNamingInfo_t applicationNameInfo = 3;
      private rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t applicationNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> applicationNameInfoBuilder_;
      public boolean hasApplicationNameInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getApplicationNameInfo() {
        if (applicationNameInfoBuilder_ == null) {
          return applicationNameInfo_;
        } else {
          return applicationNameInfoBuilder_.getMessage();
        }
      }
      public Builder setApplicationNameInfo(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (applicationNameInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationNameInfo_ = value;
          onChanged();
        } else {
          applicationNameInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setApplicationNameInfo(
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (applicationNameInfoBuilder_ == null) {
          applicationNameInfo_ = builderForValue.build();
          onChanged();
        } else {
          applicationNameInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeApplicationNameInfo(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (applicationNameInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              applicationNameInfo_ != rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance()) {
            applicationNameInfo_ =
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.newBuilder(applicationNameInfo_).mergeFrom(value).buildPartial();
          } else {
            applicationNameInfo_ = value;
          }
          onChanged();
        } else {
          applicationNameInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearApplicationNameInfo() {
        if (applicationNameInfoBuilder_ == null) {
          applicationNameInfo_ = rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance();
          onChanged();
        } else {
          applicationNameInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder getApplicationNameInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getApplicationNameInfoFieldBuilder().getBuilder();
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getApplicationNameInfoOrBuilder() {
        if (applicationNameInfoBuilder_ != null) {
          return applicationNameInfoBuilder_.getMessageOrBuilder();
        } else {
          return applicationNameInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
          getApplicationNameInfoFieldBuilder() {
        if (applicationNameInfoBuilder_ == null) {
          applicationNameInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder>(
                  applicationNameInfo_,
                  getParentForChildren(),
                  isClean());
          applicationNameInfo_ = null;
        }
        return applicationNameInfoBuilder_;
      }
      
      // optional uint32 hopCount = 4;
      private int hopCount_ ;
      public boolean hasHopCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHopCount() {
        return hopCount_;
      }
      public Builder setHopCount(int value) {
        bitField0_ |= 0x00000008;
        hopCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearHopCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hopCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint64 timeStamp = 5;
      private long timeStamp_ ;
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getTimeStamp() {
        return timeStamp_;
      }
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000010;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .rina.object.gpb.iddResponse_t iddResponse = 6;
      private java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t> iddResponse_ =
        java.util.Collections.emptyList();
      private void ensureIddResponseIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          iddResponse_ = new java.util.ArrayList<rina.object.gpb.IDDMessage_t.iddResponse_t>(iddResponse_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.IDDMessage_t.iddResponse_t, rina.object.gpb.IDDMessage_t.iddResponse_t.Builder, rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder> iddResponseBuilder_;
      
      public java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t> getIddResponseList() {
        if (iddResponseBuilder_ == null) {
          return java.util.Collections.unmodifiableList(iddResponse_);
        } else {
          return iddResponseBuilder_.getMessageList();
        }
      }
      public int getIddResponseCount() {
        if (iddResponseBuilder_ == null) {
          return iddResponse_.size();
        } else {
          return iddResponseBuilder_.getCount();
        }
      }
      public rina.object.gpb.IDDMessage_t.iddResponse_t getIddResponse(int index) {
        if (iddResponseBuilder_ == null) {
          return iddResponse_.get(index);
        } else {
          return iddResponseBuilder_.getMessage(index);
        }
      }
      public Builder setIddResponse(
          int index, rina.object.gpb.IDDMessage_t.iddResponse_t value) {
        if (iddResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIddResponseIsMutable();
          iddResponse_.set(index, value);
          onChanged();
        } else {
          iddResponseBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setIddResponse(
          int index, rina.object.gpb.IDDMessage_t.iddResponse_t.Builder builderForValue) {
        if (iddResponseBuilder_ == null) {
          ensureIddResponseIsMutable();
          iddResponse_.set(index, builderForValue.build());
          onChanged();
        } else {
          iddResponseBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addIddResponse(rina.object.gpb.IDDMessage_t.iddResponse_t value) {
        if (iddResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIddResponseIsMutable();
          iddResponse_.add(value);
          onChanged();
        } else {
          iddResponseBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addIddResponse(
          int index, rina.object.gpb.IDDMessage_t.iddResponse_t value) {
        if (iddResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIddResponseIsMutable();
          iddResponse_.add(index, value);
          onChanged();
        } else {
          iddResponseBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addIddResponse(
          rina.object.gpb.IDDMessage_t.iddResponse_t.Builder builderForValue) {
        if (iddResponseBuilder_ == null) {
          ensureIddResponseIsMutable();
          iddResponse_.add(builderForValue.build());
          onChanged();
        } else {
          iddResponseBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addIddResponse(
          int index, rina.object.gpb.IDDMessage_t.iddResponse_t.Builder builderForValue) {
        if (iddResponseBuilder_ == null) {
          ensureIddResponseIsMutable();
          iddResponse_.add(index, builderForValue.build());
          onChanged();
        } else {
          iddResponseBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllIddResponse(
          java.lang.Iterable<? extends rina.object.gpb.IDDMessage_t.iddResponse_t> values) {
        if (iddResponseBuilder_ == null) {
          ensureIddResponseIsMutable();
          super.addAll(values, iddResponse_);
          onChanged();
        } else {
          iddResponseBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearIddResponse() {
        if (iddResponseBuilder_ == null) {
          iddResponse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          iddResponseBuilder_.clear();
        }
        return this;
      }
      public Builder removeIddResponse(int index) {
        if (iddResponseBuilder_ == null) {
          ensureIddResponseIsMutable();
          iddResponse_.remove(index);
          onChanged();
        } else {
          iddResponseBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.IDDMessage_t.iddResponse_t.Builder getIddResponseBuilder(
          int index) {
        return getIddResponseFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder getIddResponseOrBuilder(
          int index) {
        if (iddResponseBuilder_ == null) {
          return iddResponse_.get(index);  } else {
          return iddResponseBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder> 
           getIddResponseOrBuilderList() {
        if (iddResponseBuilder_ != null) {
          return iddResponseBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(iddResponse_);
        }
      }
      public rina.object.gpb.IDDMessage_t.iddResponse_t.Builder addIddResponseBuilder() {
        return getIddResponseFieldBuilder().addBuilder(
            rina.object.gpb.IDDMessage_t.iddResponse_t.getDefaultInstance());
      }
      public rina.object.gpb.IDDMessage_t.iddResponse_t.Builder addIddResponseBuilder(
          int index) {
        return getIddResponseFieldBuilder().addBuilder(
            index, rina.object.gpb.IDDMessage_t.iddResponse_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.IDDMessage_t.iddResponse_t.Builder> 
           getIddResponseBuilderList() {
        return getIddResponseFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.IDDMessage_t.iddResponse_t, rina.object.gpb.IDDMessage_t.iddResponse_t.Builder, rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder> 
          getIddResponseFieldBuilder() {
        if (iddResponseBuilder_ == null) {
          iddResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.IDDMessage_t.iddResponse_t, rina.object.gpb.IDDMessage_t.iddResponse_t.Builder, rina.object.gpb.IDDMessage_t.iddResponse_tOrBuilder>(
                  iddResponse_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          iddResponse_ = null;
        }
        return iddResponseBuilder_;
      }
      
      // optional string difName = 7;
      private java.lang.Object difName_ = "";
      public boolean hasDifName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getDifName() {
        java.lang.Object ref = difName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          difName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDifName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        difName_ = value;
        onChanged();
        return this;
      }
      public Builder clearDifName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        difName_ = getDefaultInstance().getDifName();
        onChanged();
        return this;
      }
      void setDifName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        difName_ = value;
        onChanged();
      }
      
      // repeated .rina.object.gpb.applicationProcessNamingInfo_t authenticatorNameInfo = 8;
      private java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> authenticatorNameInfo_ =
        java.util.Collections.emptyList();
      private void ensureAuthenticatorNameInfoIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          authenticatorNameInfo_ = new java.util.ArrayList<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t>(authenticatorNameInfo_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> authenticatorNameInfoBuilder_;
      
      public java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> getAuthenticatorNameInfoList() {
        if (authenticatorNameInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(authenticatorNameInfo_);
        } else {
          return authenticatorNameInfoBuilder_.getMessageList();
        }
      }
      public int getAuthenticatorNameInfoCount() {
        if (authenticatorNameInfoBuilder_ == null) {
          return authenticatorNameInfo_.size();
        } else {
          return authenticatorNameInfoBuilder_.getCount();
        }
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t getAuthenticatorNameInfo(int index) {
        if (authenticatorNameInfoBuilder_ == null) {
          return authenticatorNameInfo_.get(index);
        } else {
          return authenticatorNameInfoBuilder_.getMessage(index);
        }
      }
      public Builder setAuthenticatorNameInfo(
          int index, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (authenticatorNameInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.set(index, value);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAuthenticatorNameInfo(
          int index, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (authenticatorNameInfoBuilder_ == null) {
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAuthenticatorNameInfo(rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (authenticatorNameInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.add(value);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAuthenticatorNameInfo(
          int index, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t value) {
        if (authenticatorNameInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.add(index, value);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAuthenticatorNameInfo(
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (authenticatorNameInfoBuilder_ == null) {
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.add(builderForValue.build());
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAuthenticatorNameInfo(
          int index, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder builderForValue) {
        if (authenticatorNameInfoBuilder_ == null) {
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAuthenticatorNameInfo(
          java.lang.Iterable<? extends rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t> values) {
        if (authenticatorNameInfoBuilder_ == null) {
          ensureAuthenticatorNameInfoIsMutable();
          super.addAll(values, authenticatorNameInfo_);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAuthenticatorNameInfo() {
        if (authenticatorNameInfoBuilder_ == null) {
          authenticatorNameInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeAuthenticatorNameInfo(int index) {
        if (authenticatorNameInfoBuilder_ == null) {
          ensureAuthenticatorNameInfoIsMutable();
          authenticatorNameInfo_.remove(index);
          onChanged();
        } else {
          authenticatorNameInfoBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder getAuthenticatorNameInfoBuilder(
          int index) {
        return getAuthenticatorNameInfoFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder getAuthenticatorNameInfoOrBuilder(
          int index) {
        if (authenticatorNameInfoBuilder_ == null) {
          return authenticatorNameInfo_.get(index);  } else {
          return authenticatorNameInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
           getAuthenticatorNameInfoOrBuilderList() {
        if (authenticatorNameInfoBuilder_ != null) {
          return authenticatorNameInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(authenticatorNameInfo_);
        }
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder addAuthenticatorNameInfoBuilder() {
        return getAuthenticatorNameInfoFieldBuilder().addBuilder(
            rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance());
      }
      public rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder addAuthenticatorNameInfoBuilder(
          int index) {
        return getAuthenticatorNameInfoFieldBuilder().addBuilder(
            index, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder> 
           getAuthenticatorNameInfoBuilderList() {
        return getAuthenticatorNameInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder> 
          getAuthenticatorNameInfoFieldBuilder() {
        if (authenticatorNameInfoBuilder_ == null) {
          authenticatorNameInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_t.Builder, rina.object.gpb.ApplicationProcessNamingInfoMessage_t.applicationProcessNamingInfo_tOrBuilder>(
                  authenticatorNameInfo_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          authenticatorNameInfo_ = null;
        }
        return authenticatorNameInfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.iddMessage_t)
    }
    
    static {
      defaultInstance = new iddMessage_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.iddMessage_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_iddResponse_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_iddResponse_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_iddMessage_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_iddMessage_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014IDDMessage_t\022\017rina.object.gpb\032)Applica" +
      "tionProcessNamingInfoMessage.proto\"\211\001\n\ri" +
      "ddResponse_t\022\017\n\007difName\030\001 \001(\t\022K\n\022ipcProc" +
      "essNameInfo\030\002 \001(\0132/.rina.object.gpb.appl" +
      "icationProcessNamingInfo_t\022\032\n\022supporting" +
      "DIFNames\030\003 \003(\t\"\322\002\n\014iddMessage_t\022)\n\006opCod" +
      "e\030\001 \002(\0162\031.rina.object.gpb.opCode_t\022\016\n\006re" +
      "sult\030\002 \001(\r\022L\n\023applicationNameInfo\030\003 \001(\0132" +
      "/.rina.object.gpb.applicationProcessNami" +
      "ngInfo_t\022\020\n\010hopCount\030\004 \001(\r\022\021\n\ttimeStamp\030",
      "\005 \001(\004\0223\n\013iddResponse\030\006 \003(\0132\036.rina.object" +
      ".gpb.iddResponse_t\022\017\n\007difName\030\007 \001(\t\022N\n\025a" +
      "uthenticatorNameInfo\030\010 \003(\0132/.rina.object" +
      ".gpb.applicationProcessNamingInfo_t*3\n\010o" +
      "pCode_t\022\013\n\007Request\020\000\022\014\n\010Response\020\001\022\014\n\010Re" +
      "gister\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_object_gpb_iddResponse_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_object_gpb_iddResponse_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_iddResponse_t_descriptor,
              new java.lang.String[] { "DifName", "IpcProcessNameInfo", "SupportingDIFNames", },
              rina.object.gpb.IDDMessage_t.iddResponse_t.class,
              rina.object.gpb.IDDMessage_t.iddResponse_t.Builder.class);
          internal_static_rina_object_gpb_iddMessage_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_object_gpb_iddMessage_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_iddMessage_t_descriptor,
              new java.lang.String[] { "OpCode", "Result", "ApplicationNameInfo", "HopCount", "TimeStamp", "IddResponse", "DifName", "AuthenticatorNameInfo", },
              rina.object.gpb.IDDMessage_t.iddMessage_t.class,
              rina.object.gpb.IDDMessage_t.iddMessage_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.object.gpb.ApplicationProcessNamingInfoMessage_t.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
