/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LinkStateRoutingEntry_t.proto

package rina.object.gpb;

public final class LinkStateRoutingEntrySet_t {
  private LinkStateRoutingEntrySet_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface routingEntrySet_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 addr = 1;
    boolean hasAddr();
    long getAddr();
    
    // repeated .rina.object.gpb.routingEntry_t routingEntrySet = 2;
    java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> 
        getRoutingEntrySetList();
    rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t getRoutingEntrySet(int index);
    int getRoutingEntrySetCount();
    java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder> 
        getRoutingEntrySetOrBuilderList();
    rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder getRoutingEntrySetOrBuilder(
        int index);
    
    // required uint64 timestamp = 3;
    boolean hasTimestamp();
    long getTimestamp();
  }
  public static final class routingEntrySet_t extends
      com.google.protobuf.GeneratedMessage
      implements routingEntrySet_tOrBuilder {
    // Use routingEntrySet_t.newBuilder() to construct.
    private routingEntrySet_t(Builder builder) {
      super(builder);
    }
    private routingEntrySet_t(boolean noInit) {}
    
    private static final routingEntrySet_t defaultInstance;
    public static routingEntrySet_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public routingEntrySet_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySet_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySet_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 addr = 1;
    public static final int ADDR_FIELD_NUMBER = 1;
    private long addr_;
    public boolean hasAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getAddr() {
      return addr_;
    }
    
    // repeated .rina.object.gpb.routingEntry_t routingEntrySet = 2;
    public static final int ROUTINGENTRYSET_FIELD_NUMBER = 2;
    private java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> routingEntrySet_;
    public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> getRoutingEntrySetList() {
      return routingEntrySet_;
    }
    public java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder> 
        getRoutingEntrySetOrBuilderList() {
      return routingEntrySet_;
    }
    public int getRoutingEntrySetCount() {
      return routingEntrySet_.size();
    }
    public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t getRoutingEntrySet(int index) {
      return routingEntrySet_.get(index);
    }
    public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder getRoutingEntrySetOrBuilder(
        int index) {
      return routingEntrySet_.get(index);
    }
    
    // required uint64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      addr_ = 0L;
      routingEntrySet_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRoutingEntrySetCount(); i++) {
        if (!getRoutingEntrySet(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, addr_);
      }
      for (int i = 0; i < routingEntrySet_.size(); i++) {
        output.writeMessage(2, routingEntrySet_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, addr_);
      }
      for (int i = 0; i < routingEntrySet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, routingEntrySet_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySet_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySet_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.LinkStateRoutingEntryT.routingEntrySet_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoutingEntrySetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        addr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (routingEntrySetBuilder_ == null) {
          routingEntrySet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          routingEntrySetBuilder_.clear();
        }
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.getDescriptor();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t getDefaultInstanceForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.getDefaultInstance();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t build() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t buildPartial() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t result = new rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.addr_ = addr_;
        if (routingEntrySetBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            routingEntrySet_ = java.util.Collections.unmodifiableList(routingEntrySet_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.routingEntrySet_ = routingEntrySet_;
        } else {
          result.routingEntrySet_ = routingEntrySetBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t) {
          return mergeFrom((rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t other) {
        if (other == rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.getDefaultInstance()) return this;
        if (other.hasAddr()) {
          setAddr(other.getAddr());
        }
        if (routingEntrySetBuilder_ == null) {
          if (!other.routingEntrySet_.isEmpty()) {
            if (routingEntrySet_.isEmpty()) {
              routingEntrySet_ = other.routingEntrySet_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRoutingEntrySetIsMutable();
              routingEntrySet_.addAll(other.routingEntrySet_);
            }
            onChanged();
          }
        } else {
          if (!other.routingEntrySet_.isEmpty()) {
            if (routingEntrySetBuilder_.isEmpty()) {
              routingEntrySetBuilder_.dispose();
              routingEntrySetBuilder_ = null;
              routingEntrySet_ = other.routingEntrySet_;
              bitField0_ = (bitField0_ & ~0x00000002);
              routingEntrySetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutingEntrySetFieldBuilder() : null;
            } else {
              routingEntrySetBuilder_.addAllMessages(other.routingEntrySet_);
            }
          }
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddr()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getRoutingEntrySetCount(); i++) {
          if (!getRoutingEntrySet(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              addr_ = input.readUInt64();
              break;
            }
            case 18: {
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder subBuilder = rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRoutingEntrySet(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 addr = 1;
      private long addr_ ;
      public boolean hasAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getAddr() {
        return addr_;
      }
      public Builder setAddr(long value) {
        bitField0_ |= 0x00000001;
        addr_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        addr_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .rina.object.gpb.routingEntry_t routingEntrySet = 2;
      private java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> routingEntrySet_ =
        java.util.Collections.emptyList();
      private void ensureRoutingEntrySetIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          routingEntrySet_ = new java.util.ArrayList<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t>(routingEntrySet_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder> routingEntrySetBuilder_;
      
      public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> getRoutingEntrySetList() {
        if (routingEntrySetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingEntrySet_);
        } else {
          return routingEntrySetBuilder_.getMessageList();
        }
      }
      public int getRoutingEntrySetCount() {
        if (routingEntrySetBuilder_ == null) {
          return routingEntrySet_.size();
        } else {
          return routingEntrySetBuilder_.getCount();
        }
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t getRoutingEntrySet(int index) {
        if (routingEntrySetBuilder_ == null) {
          return routingEntrySet_.get(index);
        } else {
          return routingEntrySetBuilder_.getMessage(index);
        }
      }
      public Builder setRoutingEntrySet(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t value) {
        if (routingEntrySetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.set(index, value);
          onChanged();
        } else {
          routingEntrySetBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRoutingEntrySet(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder builderForValue) {
        if (routingEntrySetBuilder_ == null) {
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingEntrySetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingEntrySet(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t value) {
        if (routingEntrySetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.add(value);
          onChanged();
        } else {
          routingEntrySetBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRoutingEntrySet(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t value) {
        if (routingEntrySetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.add(index, value);
          onChanged();
        } else {
          routingEntrySetBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRoutingEntrySet(
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder builderForValue) {
        if (routingEntrySetBuilder_ == null) {
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.add(builderForValue.build());
          onChanged();
        } else {
          routingEntrySetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingEntrySet(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder builderForValue) {
        if (routingEntrySetBuilder_ == null) {
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingEntrySetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRoutingEntrySet(
          java.lang.Iterable<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t> values) {
        if (routingEntrySetBuilder_ == null) {
          ensureRoutingEntrySetIsMutable();
          super.addAll(values, routingEntrySet_);
          onChanged();
        } else {
          routingEntrySetBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRoutingEntrySet() {
        if (routingEntrySetBuilder_ == null) {
          routingEntrySet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          routingEntrySetBuilder_.clear();
        }
        return this;
      }
      public Builder removeRoutingEntrySet(int index) {
        if (routingEntrySetBuilder_ == null) {
          ensureRoutingEntrySetIsMutable();
          routingEntrySet_.remove(index);
          onChanged();
        } else {
          routingEntrySetBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder getRoutingEntrySetBuilder(
          int index) {
        return getRoutingEntrySetFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder getRoutingEntrySetOrBuilder(
          int index) {
        if (routingEntrySetBuilder_ == null) {
          return routingEntrySet_.get(index);  } else {
          return routingEntrySetBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder> 
           getRoutingEntrySetOrBuilderList() {
        if (routingEntrySetBuilder_ != null) {
          return routingEntrySetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingEntrySet_);
        }
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder addRoutingEntrySetBuilder() {
        return getRoutingEntrySetFieldBuilder().addBuilder(
            rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.getDefaultInstance());
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder addRoutingEntrySetBuilder(
          int index) {
        return getRoutingEntrySetFieldBuilder().addBuilder(
            index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder> 
           getRoutingEntrySetBuilderList() {
        return getRoutingEntrySetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder> 
          getRoutingEntrySetFieldBuilder() {
        if (routingEntrySetBuilder_ == null) {
          routingEntrySetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder>(
                  routingEntrySet_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          routingEntrySet_ = null;
        }
        return routingEntrySetBuilder_;
      }
      
      // required uint64 timestamp = 3;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.routingEntrySet_t)
    }
    
    static {
      defaultInstance = new routingEntrySet_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.routingEntrySet_t)
  }
  
  public interface routingEntry_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 srcAddr = 1;
    boolean hasSrcAddr();
    long getSrcAddr();
    
    // required uint64 dstAddr = 2;
    boolean hasDstAddr();
    long getDstAddr();
    
    // required double cost = 3;
    boolean hasCost();
    double getCost();
    
    // required uint64 timestamp = 4;
    boolean hasTimestamp();
    long getTimestamp();
  }
  public static final class routingEntry_t extends
      com.google.protobuf.GeneratedMessage
      implements routingEntry_tOrBuilder {
    // Use routingEntry_t.newBuilder() to construct.
    private routingEntry_t(Builder builder) {
      super(builder);
    }
    private routingEntry_t(boolean noInit) {}
    
    private static final routingEntry_t defaultInstance;
    public static routingEntry_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public routingEntry_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntry_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntry_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 srcAddr = 1;
    public static final int SRCADDR_FIELD_NUMBER = 1;
    private long srcAddr_;
    public boolean hasSrcAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSrcAddr() {
      return srcAddr_;
    }
    
    // required uint64 dstAddr = 2;
    public static final int DSTADDR_FIELD_NUMBER = 2;
    private long dstAddr_;
    public boolean hasDstAddr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getDstAddr() {
      return dstAddr_;
    }
    
    // required double cost = 3;
    public static final int COST_FIELD_NUMBER = 3;
    private double cost_;
    public boolean hasCost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getCost() {
      return cost_;
    }
    
    // required uint64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      srcAddr_ = 0L;
      dstAddr_ = 0L;
      cost_ = 0D;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSrcAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDstAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, srcAddr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, dstAddr_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, cost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, srcAddr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, dstAddr_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, cost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntry_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntry_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.LinkStateRoutingEntryT.routingEntry_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        srcAddr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        dstAddr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        cost_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.getDescriptor();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t getDefaultInstanceForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.getDefaultInstance();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t build() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t buildPartial() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t result = new rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.srcAddr_ = srcAddr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dstAddr_ = dstAddr_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t) {
          return mergeFrom((rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t other) {
        if (other == rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.getDefaultInstance()) return this;
        if (other.hasSrcAddr()) {
          setSrcAddr(other.getSrcAddr());
        }
        if (other.hasDstAddr()) {
          setDstAddr(other.getDstAddr());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSrcAddr()) {
          
          return false;
        }
        if (!hasDstAddr()) {
          
          return false;
        }
        if (!hasCost()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              srcAddr_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dstAddr_ = input.readUInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              cost_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 srcAddr = 1;
      private long srcAddr_ ;
      public boolean hasSrcAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSrcAddr() {
        return srcAddr_;
      }
      public Builder setSrcAddr(long value) {
        bitField0_ |= 0x00000001;
        srcAddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcAddr_ = 0L;
        onChanged();
        return this;
      }
      
      // required uint64 dstAddr = 2;
      private long dstAddr_ ;
      public boolean hasDstAddr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getDstAddr() {
        return dstAddr_;
      }
      public Builder setDstAddr(long value) {
        bitField0_ |= 0x00000002;
        dstAddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearDstAddr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dstAddr_ = 0L;
        onChanged();
        return this;
      }
      
      // required double cost = 3;
      private double cost_ ;
      public boolean hasCost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getCost() {
        return cost_;
      }
      public Builder setCost(double value) {
        bitField0_ |= 0x00000004;
        cost_ = value;
        onChanged();
        return this;
      }
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cost_ = 0D;
        onChanged();
        return this;
      }
      
      // required uint64 timestamp = 4;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.routingEntry_t)
    }
    
    static {
      defaultInstance = new routingEntry_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.routingEntry_t)
  }
  
  public interface routingEntrySetForwardedByNeighbor_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rina.object.gpb.routingEntrySet_t routingEntrySetForwardedByNeighbor = 1;
    java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> 
        getRoutingEntrySetForwardedByNeighborList();
    rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t getRoutingEntrySetForwardedByNeighbor(int index);
    int getRoutingEntrySetForwardedByNeighborCount();
    java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder> 
        getRoutingEntrySetForwardedByNeighborOrBuilderList();
    rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder getRoutingEntrySetForwardedByNeighborOrBuilder(
        int index);
  }
  public static final class routingEntrySetForwardedByNeighbor_t extends
      com.google.protobuf.GeneratedMessage
      implements routingEntrySetForwardedByNeighbor_tOrBuilder {
    // Use routingEntrySetForwardedByNeighbor_t.newBuilder() to construct.
    private routingEntrySetForwardedByNeighbor_t(Builder builder) {
      super(builder);
    }
    private routingEntrySetForwardedByNeighbor_t(boolean noInit) {}
    
    private static final routingEntrySetForwardedByNeighbor_t defaultInstance;
    public static routingEntrySetForwardedByNeighbor_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public routingEntrySetForwardedByNeighbor_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_fieldAccessorTable;
    }
    
    // repeated .rina.object.gpb.routingEntrySet_t routingEntrySetForwardedByNeighbor = 1;
    public static final int ROUTINGENTRYSETFORWARDEDBYNEIGHBOR_FIELD_NUMBER = 1;
    private java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> routingEntrySetForwardedByNeighbor_;
    public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> getRoutingEntrySetForwardedByNeighborList() {
      return routingEntrySetForwardedByNeighbor_;
    }
    public java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder> 
        getRoutingEntrySetForwardedByNeighborOrBuilderList() {
      return routingEntrySetForwardedByNeighbor_;
    }
    public int getRoutingEntrySetForwardedByNeighborCount() {
      return routingEntrySetForwardedByNeighbor_.size();
    }
    public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t getRoutingEntrySetForwardedByNeighbor(int index) {
      return routingEntrySetForwardedByNeighbor_.get(index);
    }
    public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder getRoutingEntrySetForwardedByNeighborOrBuilder(
        int index) {
      return routingEntrySetForwardedByNeighbor_.get(index);
    }
    
    private void initFields() {
      routingEntrySetForwardedByNeighbor_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getRoutingEntrySetForwardedByNeighborCount(); i++) {
        if (!getRoutingEntrySetForwardedByNeighbor(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < routingEntrySetForwardedByNeighbor_.size(); i++) {
        output.writeMessage(1, routingEntrySetForwardedByNeighbor_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < routingEntrySetForwardedByNeighbor_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, routingEntrySetForwardedByNeighbor_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.LinkStateRoutingEntryT.routingEntrySetForwardedByNeighbor_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoutingEntrySetForwardedByNeighborFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          routingEntrySetForwardedByNeighbor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          routingEntrySetForwardedByNeighborBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t.getDescriptor();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t getDefaultInstanceForType() {
        return rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t.getDefaultInstance();
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t build() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t buildPartial() {
        rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t result = new rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t(this);
        int from_bitField0_ = bitField0_;
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            routingEntrySetForwardedByNeighbor_ = java.util.Collections.unmodifiableList(routingEntrySetForwardedByNeighbor_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.routingEntrySetForwardedByNeighbor_ = routingEntrySetForwardedByNeighbor_;
        } else {
          result.routingEntrySetForwardedByNeighbor_ = routingEntrySetForwardedByNeighborBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t) {
          return mergeFrom((rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t other) {
        if (other == rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t.getDefaultInstance()) return this;
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          if (!other.routingEntrySetForwardedByNeighbor_.isEmpty()) {
            if (routingEntrySetForwardedByNeighbor_.isEmpty()) {
              routingEntrySetForwardedByNeighbor_ = other.routingEntrySetForwardedByNeighbor_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoutingEntrySetForwardedByNeighborIsMutable();
              routingEntrySetForwardedByNeighbor_.addAll(other.routingEntrySetForwardedByNeighbor_);
            }
            onChanged();
          }
        } else {
          if (!other.routingEntrySetForwardedByNeighbor_.isEmpty()) {
            if (routingEntrySetForwardedByNeighborBuilder_.isEmpty()) {
              routingEntrySetForwardedByNeighborBuilder_.dispose();
              routingEntrySetForwardedByNeighborBuilder_ = null;
              routingEntrySetForwardedByNeighbor_ = other.routingEntrySetForwardedByNeighbor_;
              bitField0_ = (bitField0_ & ~0x00000001);
              routingEntrySetForwardedByNeighborBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutingEntrySetForwardedByNeighborFieldBuilder() : null;
            } else {
              routingEntrySetForwardedByNeighborBuilder_.addAllMessages(other.routingEntrySetForwardedByNeighbor_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getRoutingEntrySetForwardedByNeighborCount(); i++) {
          if (!getRoutingEntrySetForwardedByNeighbor(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder subBuilder = rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRoutingEntrySetForwardedByNeighbor(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rina.object.gpb.routingEntrySet_t routingEntrySetForwardedByNeighbor = 1;
      private java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> routingEntrySetForwardedByNeighbor_ =
        java.util.Collections.emptyList();
      private void ensureRoutingEntrySetForwardedByNeighborIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          routingEntrySetForwardedByNeighbor_ = new java.util.ArrayList<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t>(routingEntrySetForwardedByNeighbor_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder> routingEntrySetForwardedByNeighborBuilder_;
      
      public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> getRoutingEntrySetForwardedByNeighborList() {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingEntrySetForwardedByNeighbor_);
        } else {
          return routingEntrySetForwardedByNeighborBuilder_.getMessageList();
        }
      }
      public int getRoutingEntrySetForwardedByNeighborCount() {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          return routingEntrySetForwardedByNeighbor_.size();
        } else {
          return routingEntrySetForwardedByNeighborBuilder_.getCount();
        }
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t getRoutingEntrySetForwardedByNeighbor(int index) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          return routingEntrySetForwardedByNeighbor_.get(index);
        } else {
          return routingEntrySetForwardedByNeighborBuilder_.getMessage(index);
        }
      }
      public Builder setRoutingEntrySetForwardedByNeighbor(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t value) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.set(index, value);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRoutingEntrySetForwardedByNeighbor(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder builderForValue) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingEntrySetForwardedByNeighbor(rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t value) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.add(value);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRoutingEntrySetForwardedByNeighbor(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t value) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.add(index, value);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRoutingEntrySetForwardedByNeighbor(
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder builderForValue) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.add(builderForValue.build());
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingEntrySetForwardedByNeighbor(
          int index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder builderForValue) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRoutingEntrySetForwardedByNeighbor(
          java.lang.Iterable<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t> values) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          super.addAll(values, routingEntrySetForwardedByNeighbor_);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRoutingEntrySetForwardedByNeighbor() {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          routingEntrySetForwardedByNeighbor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.clear();
        }
        return this;
      }
      public Builder removeRoutingEntrySetForwardedByNeighbor(int index) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          ensureRoutingEntrySetForwardedByNeighborIsMutable();
          routingEntrySetForwardedByNeighbor_.remove(index);
          onChanged();
        } else {
          routingEntrySetForwardedByNeighborBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder getRoutingEntrySetForwardedByNeighborBuilder(
          int index) {
        return getRoutingEntrySetForwardedByNeighborFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder getRoutingEntrySetForwardedByNeighborOrBuilder(
          int index) {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          return routingEntrySetForwardedByNeighbor_.get(index);  } else {
          return routingEntrySetForwardedByNeighborBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder> 
           getRoutingEntrySetForwardedByNeighborOrBuilderList() {
        if (routingEntrySetForwardedByNeighborBuilder_ != null) {
          return routingEntrySetForwardedByNeighborBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingEntrySetForwardedByNeighbor_);
        }
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder addRoutingEntrySetForwardedByNeighborBuilder() {
        return getRoutingEntrySetForwardedByNeighborFieldBuilder().addBuilder(
            rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.getDefaultInstance());
      }
      public rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder addRoutingEntrySetForwardedByNeighborBuilder(
          int index) {
        return getRoutingEntrySetForwardedByNeighborFieldBuilder().addBuilder(
            index, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder> 
           getRoutingEntrySetForwardedByNeighborBuilderList() {
        return getRoutingEntrySetForwardedByNeighborFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder> 
          getRoutingEntrySetForwardedByNeighborFieldBuilder() {
        if (routingEntrySetForwardedByNeighborBuilder_ == null) {
          routingEntrySetForwardedByNeighborBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder, rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_tOrBuilder>(
                  routingEntrySetForwardedByNeighbor_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          routingEntrySetForwardedByNeighbor_ = null;
        }
        return routingEntrySetForwardedByNeighborBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.routingEntrySetForwardedByNeighbor_t)
    }
    
    static {
      defaultInstance = new routingEntrySetForwardedByNeighbor_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.routingEntrySetForwardedByNeighbor_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_routingEntrySet_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_routingEntrySet_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_routingEntry_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_routingEntry_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035LinkStateRoutingEntry_t.proto\022\017rina.ob" +
      "ject.gpb\"n\n\021routingEntrySet_t\022\014\n\004addr\030\001 " +
      "\002(\004\0228\n\017routingEntrySet\030\002 \003(\0132\037.rina.obje" +
      "ct.gpb.routingEntry_t\022\021\n\ttimestamp\030\003 \002(\004" +
      "\"S\n\016routingEntry_t\022\017\n\007srcAddr\030\001 \002(\004\022\017\n\007d" +
      "stAddr\030\002 \002(\004\022\014\n\004cost\030\003 \002(\001\022\021\n\ttimestamp\030" +
      "\004 \002(\004\"v\n$routingEntrySetForwardedByNeigh" +
      "bor_t\022N\n\"routingEntrySetForwardedByNeigh" +
      "bor\030\001 \003(\0132\".rina.object.gpb.routingEntry" +
      "Set_t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_object_gpb_routingEntrySet_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_object_gpb_routingEntrySet_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_routingEntrySet_t_descriptor,
              new java.lang.String[] { "Addr", "RoutingEntrySet", "Timestamp", },
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.class,
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySet_t.Builder.class);
          internal_static_rina_object_gpb_routingEntry_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_object_gpb_routingEntry_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_routingEntry_t_descriptor,
              new java.lang.String[] { "SrcAddr", "DstAddr", "Cost", "Timestamp", },
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.class,
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntry_t.Builder.class);
          internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_routingEntrySetForwardedByNeighbor_t_descriptor,
              new java.lang.String[] { "RoutingEntrySetForwardedByNeighbor", },
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t.class,
              rina.object.gpb.LinkStateRoutingEntrySet_t.routingEntrySetForwardedByNeighbor_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
