/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Member_t.proto

package rina.object.gpb;

public final class Member_t {
  private Member_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface members_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rina.object.gpb.member_t member = 1;
    java.util.List<rina.object.gpb.Member_t.member_t> 
        getMemberList();
    rina.object.gpb.Member_t.member_t getMember(int index);
    int getMemberCount();
    java.util.List<? extends rina.object.gpb.Member_t.member_tOrBuilder> 
        getMemberOrBuilderList();
    rina.object.gpb.Member_t.member_tOrBuilder getMemberOrBuilder(
        int index);
  }
  public static final class members_t extends
      com.google.protobuf.GeneratedMessage
      implements members_tOrBuilder {
    // Use members_t.newBuilder() to construct.
    private members_t(Builder builder) {
      super(builder);
    }
    private members_t(boolean noInit) {}
    
    private static final members_t defaultInstance;
    public static members_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public members_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.Member_t.internal_static_rina_object_gpb_members_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.Member_t.internal_static_rina_object_gpb_members_t_fieldAccessorTable;
    }
    
    // repeated .rina.object.gpb.member_t member = 1;
    public static final int MEMBER_FIELD_NUMBER = 1;
    private java.util.List<rina.object.gpb.Member_t.member_t> member_;
    public java.util.List<rina.object.gpb.Member_t.member_t> getMemberList() {
      return member_;
    }
    public java.util.List<? extends rina.object.gpb.Member_t.member_tOrBuilder> 
        getMemberOrBuilderList() {
      return member_;
    }
    public int getMemberCount() {
      return member_.size();
    }
    public rina.object.gpb.Member_t.member_t getMember(int index) {
      return member_.get(index);
    }
    public rina.object.gpb.Member_t.member_tOrBuilder getMemberOrBuilder(
        int index) {
      return member_.get(index);
    }
    
    private void initFields() {
      member_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < member_.size(); i++) {
        output.writeMessage(1, member_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < member_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, member_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.Member_t.members_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Member_t.members_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Member_t.members_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.Member_t.members_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.Member_t.members_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.Member_t.internal_static_rina_object_gpb_members_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.Member_t.internal_static_rina_object_gpb_members_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.MemberT.members_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMemberFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (memberBuilder_ == null) {
          member_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          memberBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.Member_t.members_t.getDescriptor();
      }
      
      public rina.object.gpb.Member_t.members_t getDefaultInstanceForType() {
        return rina.object.gpb.Member_t.members_t.getDefaultInstance();
      }
      
      public rina.object.gpb.Member_t.members_t build() {
        rina.object.gpb.Member_t.members_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.Member_t.members_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.Member_t.members_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.Member_t.members_t buildPartial() {
        rina.object.gpb.Member_t.members_t result = new rina.object.gpb.Member_t.members_t(this);
        int from_bitField0_ = bitField0_;
        if (memberBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            member_ = java.util.Collections.unmodifiableList(member_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.member_ = member_;
        } else {
          result.member_ = memberBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.Member_t.members_t) {
          return mergeFrom((rina.object.gpb.Member_t.members_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.Member_t.members_t other) {
        if (other == rina.object.gpb.Member_t.members_t.getDefaultInstance()) return this;
        if (memberBuilder_ == null) {
          if (!other.member_.isEmpty()) {
            if (member_.isEmpty()) {
              member_ = other.member_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMemberIsMutable();
              member_.addAll(other.member_);
            }
            onChanged();
          }
        } else {
          if (!other.member_.isEmpty()) {
            if (memberBuilder_.isEmpty()) {
              memberBuilder_.dispose();
              memberBuilder_ = null;
              member_ = other.member_;
              bitField0_ = (bitField0_ & ~0x00000001);
              memberBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMemberFieldBuilder() : null;
            } else {
              memberBuilder_.addAllMessages(other.member_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rina.object.gpb.Member_t.member_t.Builder subBuilder = rina.object.gpb.Member_t.member_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMember(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rina.object.gpb.member_t member = 1;
      private java.util.List<rina.object.gpb.Member_t.member_t> member_ =
        java.util.Collections.emptyList();
      private void ensureMemberIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          member_ = new java.util.ArrayList<rina.object.gpb.Member_t.member_t>(member_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.Member_t.member_t, rina.object.gpb.Member_t.member_t.Builder, rina.object.gpb.Member_t.member_tOrBuilder> memberBuilder_;
      
      public java.util.List<rina.object.gpb.Member_t.member_t> getMemberList() {
        if (memberBuilder_ == null) {
          return java.util.Collections.unmodifiableList(member_);
        } else {
          return memberBuilder_.getMessageList();
        }
      }
      public int getMemberCount() {
        if (memberBuilder_ == null) {
          return member_.size();
        } else {
          return memberBuilder_.getCount();
        }
      }
      public rina.object.gpb.Member_t.member_t getMember(int index) {
        if (memberBuilder_ == null) {
          return member_.get(index);
        } else {
          return memberBuilder_.getMessage(index);
        }
      }
      public Builder setMember(
          int index, rina.object.gpb.Member_t.member_t value) {
        if (memberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberIsMutable();
          member_.set(index, value);
          onChanged();
        } else {
          memberBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMember(
          int index, rina.object.gpb.Member_t.member_t.Builder builderForValue) {
        if (memberBuilder_ == null) {
          ensureMemberIsMutable();
          member_.set(index, builderForValue.build());
          onChanged();
        } else {
          memberBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMember(rina.object.gpb.Member_t.member_t value) {
        if (memberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberIsMutable();
          member_.add(value);
          onChanged();
        } else {
          memberBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMember(
          int index, rina.object.gpb.Member_t.member_t value) {
        if (memberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberIsMutable();
          member_.add(index, value);
          onChanged();
        } else {
          memberBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMember(
          rina.object.gpb.Member_t.member_t.Builder builderForValue) {
        if (memberBuilder_ == null) {
          ensureMemberIsMutable();
          member_.add(builderForValue.build());
          onChanged();
        } else {
          memberBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMember(
          int index, rina.object.gpb.Member_t.member_t.Builder builderForValue) {
        if (memberBuilder_ == null) {
          ensureMemberIsMutable();
          member_.add(index, builderForValue.build());
          onChanged();
        } else {
          memberBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMember(
          java.lang.Iterable<? extends rina.object.gpb.Member_t.member_t> values) {
        if (memberBuilder_ == null) {
          ensureMemberIsMutable();
          super.addAll(values, member_);
          onChanged();
        } else {
          memberBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMember() {
        if (memberBuilder_ == null) {
          member_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          memberBuilder_.clear();
        }
        return this;
      }
      public Builder removeMember(int index) {
        if (memberBuilder_ == null) {
          ensureMemberIsMutable();
          member_.remove(index);
          onChanged();
        } else {
          memberBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.Member_t.member_t.Builder getMemberBuilder(
          int index) {
        return getMemberFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.Member_t.member_tOrBuilder getMemberOrBuilder(
          int index) {
        if (memberBuilder_ == null) {
          return member_.get(index);  } else {
          return memberBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.Member_t.member_tOrBuilder> 
           getMemberOrBuilderList() {
        if (memberBuilder_ != null) {
          return memberBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(member_);
        }
      }
      public rina.object.gpb.Member_t.member_t.Builder addMemberBuilder() {
        return getMemberFieldBuilder().addBuilder(
            rina.object.gpb.Member_t.member_t.getDefaultInstance());
      }
      public rina.object.gpb.Member_t.member_t.Builder addMemberBuilder(
          int index) {
        return getMemberFieldBuilder().addBuilder(
            index, rina.object.gpb.Member_t.member_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.Member_t.member_t.Builder> 
           getMemberBuilderList() {
        return getMemberFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.Member_t.member_t, rina.object.gpb.Member_t.member_t.Builder, rina.object.gpb.Member_t.member_tOrBuilder> 
          getMemberFieldBuilder() {
        if (memberBuilder_ == null) {
          memberBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.Member_t.member_t, rina.object.gpb.Member_t.member_t.Builder, rina.object.gpb.Member_t.member_tOrBuilder>(
                  member_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          member_ = null;
        }
        return memberBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.members_t)
    }
    
    static {
      defaultInstance = new members_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.members_t)
  }
  
  public interface member_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string applicationProcessName = 1;
    boolean hasApplicationProcessName();
    String getApplicationProcessName();
    
    // optional string applicationProcessInstance = 2;
    boolean hasApplicationProcessInstance();
    String getApplicationProcessInstance();
    
    // optional uint64 address = 3;
    boolean hasAddress();
    long getAddress();
    
    // repeated string underlyingDIFs = 4;
    java.util.List<String> getUnderlyingDIFsList();
    int getUnderlyingDIFsCount();
    String getUnderlyingDIFs(int index);
  }
  public static final class member_t extends
      com.google.protobuf.GeneratedMessage
      implements member_tOrBuilder {
    // Use member_t.newBuilder() to construct.
    private member_t(Builder builder) {
      super(builder);
    }
    private member_t(boolean noInit) {}
    
    private static final member_t defaultInstance;
    public static member_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public member_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.Member_t.internal_static_rina_object_gpb_member_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.Member_t.internal_static_rina_object_gpb_member_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string applicationProcessName = 1;
    public static final int APPLICATIONPROCESSNAME_FIELD_NUMBER = 1;
    private java.lang.Object applicationProcessName_;
    public boolean hasApplicationProcessName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getApplicationProcessName() {
      java.lang.Object ref = applicationProcessName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationProcessName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationProcessNameBytes() {
      java.lang.Object ref = applicationProcessName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationProcessName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string applicationProcessInstance = 2;
    public static final int APPLICATIONPROCESSINSTANCE_FIELD_NUMBER = 2;
    private java.lang.Object applicationProcessInstance_;
    public boolean hasApplicationProcessInstance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getApplicationProcessInstance() {
      java.lang.Object ref = applicationProcessInstance_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          applicationProcessInstance_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationProcessInstanceBytes() {
      java.lang.Object ref = applicationProcessInstance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        applicationProcessInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint64 address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private long address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getAddress() {
      return address_;
    }
    
    // repeated string underlyingDIFs = 4;
    public static final int UNDERLYINGDIFS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList underlyingDIFs_;
    public java.util.List<String>
        getUnderlyingDIFsList() {
      return underlyingDIFs_;
    }
    public int getUnderlyingDIFsCount() {
      return underlyingDIFs_.size();
    }
    public String getUnderlyingDIFs(int index) {
      return underlyingDIFs_.get(index);
    }
    
    private void initFields() {
      applicationProcessName_ = "";
      applicationProcessInstance_ = "";
      address_ = 0L;
      underlyingDIFs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getApplicationProcessNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getApplicationProcessInstanceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, address_);
      }
      for (int i = 0; i < underlyingDIFs_.size(); i++) {
        output.writeBytes(4, underlyingDIFs_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getApplicationProcessNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getApplicationProcessInstanceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, address_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < underlyingDIFs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(underlyingDIFs_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUnderlyingDIFsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.Member_t.member_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Member_t.member_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Member_t.member_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.Member_t.member_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.Member_t.member_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.Member_t.internal_static_rina_object_gpb_member_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.Member_t.internal_static_rina_object_gpb_member_t_fieldAccessorTable;
      }
      
      // Construct using rina.object.gpb.MemberT.member_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        applicationProcessName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationProcessInstance_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        underlyingDIFs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.Member_t.member_t.getDescriptor();
      }
      
      public rina.object.gpb.Member_t.member_t getDefaultInstanceForType() {
        return rina.object.gpb.Member_t.member_t.getDefaultInstance();
      }
      
      public rina.object.gpb.Member_t.member_t build() {
        rina.object.gpb.Member_t.member_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.Member_t.member_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.Member_t.member_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.Member_t.member_t buildPartial() {
        rina.object.gpb.Member_t.member_t result = new rina.object.gpb.Member_t.member_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.applicationProcessName_ = applicationProcessName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.applicationProcessInstance_ = applicationProcessInstance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          underlyingDIFs_ = new com.google.protobuf.UnmodifiableLazyStringList(
              underlyingDIFs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.underlyingDIFs_ = underlyingDIFs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.Member_t.member_t) {
          return mergeFrom((rina.object.gpb.Member_t.member_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.Member_t.member_t other) {
        if (other == rina.object.gpb.Member_t.member_t.getDefaultInstance()) return this;
        if (other.hasApplicationProcessName()) {
          setApplicationProcessName(other.getApplicationProcessName());
        }
        if (other.hasApplicationProcessInstance()) {
          setApplicationProcessInstance(other.getApplicationProcessInstance());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (!other.underlyingDIFs_.isEmpty()) {
          if (underlyingDIFs_.isEmpty()) {
            underlyingDIFs_ = other.underlyingDIFs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureUnderlyingDIFsIsMutable();
            underlyingDIFs_.addAll(other.underlyingDIFs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              applicationProcessName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              applicationProcessInstance_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              address_ = input.readUInt64();
              break;
            }
            case 34: {
              ensureUnderlyingDIFsIsMutable();
              underlyingDIFs_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string applicationProcessName = 1;
      private java.lang.Object applicationProcessName_ = "";
      public boolean hasApplicationProcessName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getApplicationProcessName() {
        java.lang.Object ref = applicationProcessName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationProcessName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationProcessName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        applicationProcessName_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationProcessName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationProcessName_ = getDefaultInstance().getApplicationProcessName();
        onChanged();
        return this;
      }
      void setApplicationProcessName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        applicationProcessName_ = value;
        onChanged();
      }
      
      // optional string applicationProcessInstance = 2;
      private java.lang.Object applicationProcessInstance_ = "";
      public boolean hasApplicationProcessInstance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getApplicationProcessInstance() {
        java.lang.Object ref = applicationProcessInstance_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          applicationProcessInstance_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplicationProcessInstance(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        applicationProcessInstance_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplicationProcessInstance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        applicationProcessInstance_ = getDefaultInstance().getApplicationProcessInstance();
        onChanged();
        return this;
      }
      void setApplicationProcessInstance(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        applicationProcessInstance_ = value;
        onChanged();
      }
      
      // optional uint64 address = 3;
      private long address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getAddress() {
        return address_;
      }
      public Builder setAddress(long value) {
        bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated string underlyingDIFs = 4;
      private com.google.protobuf.LazyStringList underlyingDIFs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUnderlyingDIFsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          underlyingDIFs_ = new com.google.protobuf.LazyStringArrayList(underlyingDIFs_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getUnderlyingDIFsList() {
        return java.util.Collections.unmodifiableList(underlyingDIFs_);
      }
      public int getUnderlyingDIFsCount() {
        return underlyingDIFs_.size();
      }
      public String getUnderlyingDIFs(int index) {
        return underlyingDIFs_.get(index);
      }
      public Builder setUnderlyingDIFs(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUnderlyingDIFsIsMutable();
        underlyingDIFs_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addUnderlyingDIFs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUnderlyingDIFsIsMutable();
        underlyingDIFs_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllUnderlyingDIFs(
          java.lang.Iterable<String> values) {
        ensureUnderlyingDIFsIsMutable();
        super.addAll(values, underlyingDIFs_);
        onChanged();
        return this;
      }
      public Builder clearUnderlyingDIFs() {
        underlyingDIFs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addUnderlyingDIFs(com.google.protobuf.ByteString value) {
        ensureUnderlyingDIFsIsMutable();
        underlyingDIFs_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rina.object.gpb.member_t)
    }
    
    static {
      defaultInstance = new member_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.object.gpb.member_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_members_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_members_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_object_gpb_member_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_object_gpb_member_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Member_t.proto\022\017rina.object.gpb\"6\n\tmem" +
      "bers_t\022)\n\006member\030\001 \003(\0132\031.rina.object.gpb" +
      ".member_t\"w\n\010member_t\022\036\n\026applicationProc" +
      "essName\030\001 \001(\t\022\"\n\032applicationProcessInsta" +
      "nce\030\002 \001(\t\022\017\n\007address\030\003 \001(\004\022\026\n\016underlying" +
      "DIFs\030\004 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_object_gpb_members_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_object_gpb_members_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_members_t_descriptor,
              new java.lang.String[] { "Member", },
              rina.object.gpb.Member_t.members_t.class,
              rina.object.gpb.Member_t.members_t.Builder.class);
          internal_static_rina_object_gpb_member_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_object_gpb_member_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_object_gpb_member_t_descriptor,
              new java.lang.String[] { "ApplicationProcessName", "ApplicationProcessInstance", "Address", "UnderlyingDIFs", },
              rina.object.gpb.Member_t.member_t.class,
              rina.object.gpb.Member_t.member_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
