/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QoSSpecification.proto

package rina.object.gpb;

public final class QoSSpecification_t {
  private QoSSpecification_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface qosSpecification_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional uint32 qosid = 2;
    boolean hasQosid();
    int getQosid();
    
    // optional uint64 averageBandwidth = 3;
    boolean hasAverageBandwidth();
    long getAverageBandwidth();
    
    // optional uint64 averageSDUBandwidth = 4;
    boolean hasAverageSDUBandwidth();
    long getAverageSDUBandwidth();
    
    // optional uint32 peakBandwidthDuration = 5;
    boolean hasPeakBandwidthDuration();
    int getPeakBandwidthDuration();
    
    // optional uint32 peakSDUBandwidthDuration = 6;
    boolean hasPeakSDUBandwidthDuration();
    int getPeakSDUBandwidthDuration();
    
    // optional double undetectedBitErrorRate = 7;
    boolean hasUndetectedBitErrorRate();
    double getUndetectedBitErrorRate();
    
    // optional bool partialDelivery = 8;
    boolean hasPartialDelivery();
    boolean getPartialDelivery();
    
    // optional bool order = 9;
    boolean hasOrder();
    boolean getOrder();
    
    // optional int32 maxAllowableGapSdu = 10;
    boolean hasMaxAllowableGapSdu();
    int getMaxAllowableGapSdu();
    
    // optional uint32 delay = 11;
    boolean hasDelay();
    int getDelay();
    
    // optional uint32 jitter = 12;
    boolean hasJitter();
    int getJitter();
    
    // repeated .rina.messages.property_t extraParameters = 13;
    java.util.List<rina.object.gpb.PropertyMessage_t.property_t> 
        getExtraParametersList();
    rina.object.gpb.PropertyMessage_t.property_t getExtraParameters(int index);
    int getExtraParametersCount();
    java.util.List<? extends rina.object.gpb.PropertyMessage_t.property_tOrBuilder> 
        getExtraParametersOrBuilderList();
    rina.object.gpb.PropertyMessage_t.property_tOrBuilder getExtraParametersOrBuilder(
        int index);
  }
  public static final class qosSpecification_t extends
      com.google.protobuf.GeneratedMessage
      implements qosSpecification_tOrBuilder {
    // Use qosSpecification_t.newBuilder() to construct.
    private qosSpecification_t(Builder builder) {
      super(builder);
    }
    private qosSpecification_t(boolean noInit) {}
    
    private static final qosSpecification_t defaultInstance;
    public static qosSpecification_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public qosSpecification_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.QoSSpecification_t.internal_static_rina_messages_qosSpecification_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.QoSSpecification_t.internal_static_rina_messages_qosSpecification_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 qosid = 2;
    public static final int QOSID_FIELD_NUMBER = 2;
    private int qosid_;
    public boolean hasQosid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getQosid() {
      return qosid_;
    }
    
    // optional uint64 averageBandwidth = 3;
    public static final int AVERAGEBANDWIDTH_FIELD_NUMBER = 3;
    private long averageBandwidth_;
    public boolean hasAverageBandwidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getAverageBandwidth() {
      return averageBandwidth_;
    }
    
    // optional uint64 averageSDUBandwidth = 4;
    public static final int AVERAGESDUBANDWIDTH_FIELD_NUMBER = 4;
    private long averageSDUBandwidth_;
    public boolean hasAverageSDUBandwidth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getAverageSDUBandwidth() {
      return averageSDUBandwidth_;
    }
    
    // optional uint32 peakBandwidthDuration = 5;
    public static final int PEAKBANDWIDTHDURATION_FIELD_NUMBER = 5;
    private int peakBandwidthDuration_;
    public boolean hasPeakBandwidthDuration() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getPeakBandwidthDuration() {
      return peakBandwidthDuration_;
    }
    
    // optional uint32 peakSDUBandwidthDuration = 6;
    public static final int PEAKSDUBANDWIDTHDURATION_FIELD_NUMBER = 6;
    private int peakSDUBandwidthDuration_;
    public boolean hasPeakSDUBandwidthDuration() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getPeakSDUBandwidthDuration() {
      return peakSDUBandwidthDuration_;
    }
    
    // optional double undetectedBitErrorRate = 7;
    public static final int UNDETECTEDBITERRORRATE_FIELD_NUMBER = 7;
    private double undetectedBitErrorRate_;
    public boolean hasUndetectedBitErrorRate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getUndetectedBitErrorRate() {
      return undetectedBitErrorRate_;
    }
    
    // optional bool partialDelivery = 8;
    public static final int PARTIALDELIVERY_FIELD_NUMBER = 8;
    private boolean partialDelivery_;
    public boolean hasPartialDelivery() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public boolean getPartialDelivery() {
      return partialDelivery_;
    }
    
    // optional bool order = 9;
    public static final int ORDER_FIELD_NUMBER = 9;
    private boolean order_;
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getOrder() {
      return order_;
    }
    
    // optional int32 maxAllowableGapSdu = 10;
    public static final int MAXALLOWABLEGAPSDU_FIELD_NUMBER = 10;
    private int maxAllowableGapSdu_;
    public boolean hasMaxAllowableGapSdu() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getMaxAllowableGapSdu() {
      return maxAllowableGapSdu_;
    }
    
    // optional uint32 delay = 11;
    public static final int DELAY_FIELD_NUMBER = 11;
    private int delay_;
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getDelay() {
      return delay_;
    }
    
    // optional uint32 jitter = 12;
    public static final int JITTER_FIELD_NUMBER = 12;
    private int jitter_;
    public boolean hasJitter() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getJitter() {
      return jitter_;
    }
    
    // repeated .rina.messages.property_t extraParameters = 13;
    public static final int EXTRAPARAMETERS_FIELD_NUMBER = 13;
    private java.util.List<rina.object.gpb.PropertyMessage_t.property_t> extraParameters_;
    public java.util.List<rina.object.gpb.PropertyMessage_t.property_t> getExtraParametersList() {
      return extraParameters_;
    }
    public java.util.List<? extends rina.object.gpb.PropertyMessage_t.property_tOrBuilder> 
        getExtraParametersOrBuilderList() {
      return extraParameters_;
    }
    public int getExtraParametersCount() {
      return extraParameters_.size();
    }
    public rina.object.gpb.PropertyMessage_t.property_t getExtraParameters(int index) {
      return extraParameters_.get(index);
    }
    public rina.object.gpb.PropertyMessage_t.property_tOrBuilder getExtraParametersOrBuilder(
        int index) {
      return extraParameters_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      qosid_ = 0;
      averageBandwidth_ = 0L;
      averageSDUBandwidth_ = 0L;
      peakBandwidthDuration_ = 0;
      peakSDUBandwidthDuration_ = 0;
      undetectedBitErrorRate_ = 0D;
      partialDelivery_ = false;
      order_ = false;
      maxAllowableGapSdu_ = 0;
      delay_ = 0;
      jitter_ = 0;
      extraParameters_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getExtraParametersCount(); i++) {
        if (!getExtraParameters(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, qosid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, averageBandwidth_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, averageSDUBandwidth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, peakBandwidthDuration_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, peakSDUBandwidthDuration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, undetectedBitErrorRate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, partialDelivery_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, order_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, maxAllowableGapSdu_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, delay_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(12, jitter_);
      }
      for (int i = 0; i < extraParameters_.size(); i++) {
        output.writeMessage(13, extraParameters_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, qosid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, averageBandwidth_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, averageSDUBandwidth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, peakBandwidthDuration_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, peakSDUBandwidthDuration_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, undetectedBitErrorRate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, partialDelivery_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, order_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, maxAllowableGapSdu_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, delay_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, jitter_);
      }
      for (int i = 0; i < extraParameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, extraParameters_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.QoSSpecification_t.qosSpecification_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.QoSSpecification_t.qosSpecification_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.QoSSpecification_t.qosSpecification_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.QoSSpecification_t.internal_static_rina_messages_qosSpecification_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.QoSSpecification_t.internal_static_rina_messages_qosSpecification_t_fieldAccessorTable;
      }
      
      // Construct using rina.messages.QoSSpecification.qosSpecification_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExtraParametersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        qosid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        averageBandwidth_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        averageSDUBandwidth_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        peakBandwidthDuration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        peakSDUBandwidthDuration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        undetectedBitErrorRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        partialDelivery_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        order_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        maxAllowableGapSdu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        jitter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        if (extraParametersBuilder_ == null) {
          extraParameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
        } else {
          extraParametersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.QoSSpecification_t.qosSpecification_t.getDescriptor();
      }
      
      public rina.object.gpb.QoSSpecification_t.qosSpecification_t getDefaultInstanceForType() {
        return rina.object.gpb.QoSSpecification_t.qosSpecification_t.getDefaultInstance();
      }
      
      public rina.object.gpb.QoSSpecification_t.qosSpecification_t build() {
        rina.object.gpb.QoSSpecification_t.qosSpecification_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.QoSSpecification_t.qosSpecification_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.QoSSpecification_t.qosSpecification_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.QoSSpecification_t.qosSpecification_t buildPartial() {
        rina.object.gpb.QoSSpecification_t.qosSpecification_t result = new rina.object.gpb.QoSSpecification_t.qosSpecification_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qosid_ = qosid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.averageBandwidth_ = averageBandwidth_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.averageSDUBandwidth_ = averageSDUBandwidth_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.peakBandwidthDuration_ = peakBandwidthDuration_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.peakSDUBandwidthDuration_ = peakSDUBandwidthDuration_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.undetectedBitErrorRate_ = undetectedBitErrorRate_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.partialDelivery_ = partialDelivery_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.order_ = order_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.maxAllowableGapSdu_ = maxAllowableGapSdu_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.delay_ = delay_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.jitter_ = jitter_;
        if (extraParametersBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000)) {
            extraParameters_ = java.util.Collections.unmodifiableList(extraParameters_);
            bitField0_ = (bitField0_ & ~0x00001000);
          }
          result.extraParameters_ = extraParameters_;
        } else {
          result.extraParameters_ = extraParametersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.QoSSpecification_t.qosSpecification_t) {
          return mergeFrom((rina.object.gpb.QoSSpecification_t.qosSpecification_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.QoSSpecification_t.qosSpecification_t other) {
        if (other == rina.object.gpb.QoSSpecification_t.qosSpecification_t.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasQosid()) {
          setQosid(other.getQosid());
        }
        if (other.hasAverageBandwidth()) {
          setAverageBandwidth(other.getAverageBandwidth());
        }
        if (other.hasAverageSDUBandwidth()) {
          setAverageSDUBandwidth(other.getAverageSDUBandwidth());
        }
        if (other.hasPeakBandwidthDuration()) {
          setPeakBandwidthDuration(other.getPeakBandwidthDuration());
        }
        if (other.hasPeakSDUBandwidthDuration()) {
          setPeakSDUBandwidthDuration(other.getPeakSDUBandwidthDuration());
        }
        if (other.hasUndetectedBitErrorRate()) {
          setUndetectedBitErrorRate(other.getUndetectedBitErrorRate());
        }
        if (other.hasPartialDelivery()) {
          setPartialDelivery(other.getPartialDelivery());
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (other.hasMaxAllowableGapSdu()) {
          setMaxAllowableGapSdu(other.getMaxAllowableGapSdu());
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        if (other.hasJitter()) {
          setJitter(other.getJitter());
        }
        if (extraParametersBuilder_ == null) {
          if (!other.extraParameters_.isEmpty()) {
            if (extraParameters_.isEmpty()) {
              extraParameters_ = other.extraParameters_;
              bitField0_ = (bitField0_ & ~0x00001000);
            } else {
              ensureExtraParametersIsMutable();
              extraParameters_.addAll(other.extraParameters_);
            }
            onChanged();
          }
        } else {
          if (!other.extraParameters_.isEmpty()) {
            if (extraParametersBuilder_.isEmpty()) {
              extraParametersBuilder_.dispose();
              extraParametersBuilder_ = null;
              extraParameters_ = other.extraParameters_;
              bitField0_ = (bitField0_ & ~0x00001000);
              extraParametersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExtraParametersFieldBuilder() : null;
            } else {
              extraParametersBuilder_.addAllMessages(other.extraParameters_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getExtraParametersCount(); i++) {
          if (!getExtraParameters(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              qosid_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              averageBandwidth_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              averageSDUBandwidth_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              peakBandwidthDuration_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              peakSDUBandwidthDuration_ = input.readUInt32();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              undetectedBitErrorRate_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              partialDelivery_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              order_ = input.readBool();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              maxAllowableGapSdu_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              delay_ = input.readUInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              jitter_ = input.readUInt32();
              break;
            }
            case 106: {
              rina.object.gpb.PropertyMessage_t.property_t.Builder subBuilder = rina.object.gpb.PropertyMessage_t.property_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExtraParameters(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional uint32 qosid = 2;
      private int qosid_ ;
      public boolean hasQosid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getQosid() {
        return qosid_;
      }
      public Builder setQosid(int value) {
        bitField0_ |= 0x00000002;
        qosid_ = value;
        onChanged();
        return this;
      }
      public Builder clearQosid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        qosid_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint64 averageBandwidth = 3;
      private long averageBandwidth_ ;
      public boolean hasAverageBandwidth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getAverageBandwidth() {
        return averageBandwidth_;
      }
      public Builder setAverageBandwidth(long value) {
        bitField0_ |= 0x00000004;
        averageBandwidth_ = value;
        onChanged();
        return this;
      }
      public Builder clearAverageBandwidth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        averageBandwidth_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 averageSDUBandwidth = 4;
      private long averageSDUBandwidth_ ;
      public boolean hasAverageSDUBandwidth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getAverageSDUBandwidth() {
        return averageSDUBandwidth_;
      }
      public Builder setAverageSDUBandwidth(long value) {
        bitField0_ |= 0x00000008;
        averageSDUBandwidth_ = value;
        onChanged();
        return this;
      }
      public Builder clearAverageSDUBandwidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        averageSDUBandwidth_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 peakBandwidthDuration = 5;
      private int peakBandwidthDuration_ ;
      public boolean hasPeakBandwidthDuration() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getPeakBandwidthDuration() {
        return peakBandwidthDuration_;
      }
      public Builder setPeakBandwidthDuration(int value) {
        bitField0_ |= 0x00000010;
        peakBandwidthDuration_ = value;
        onChanged();
        return this;
      }
      public Builder clearPeakBandwidthDuration() {
        bitField0_ = (bitField0_ & ~0x00000010);
        peakBandwidthDuration_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 peakSDUBandwidthDuration = 6;
      private int peakSDUBandwidthDuration_ ;
      public boolean hasPeakSDUBandwidthDuration() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getPeakSDUBandwidthDuration() {
        return peakSDUBandwidthDuration_;
      }
      public Builder setPeakSDUBandwidthDuration(int value) {
        bitField0_ |= 0x00000020;
        peakSDUBandwidthDuration_ = value;
        onChanged();
        return this;
      }
      public Builder clearPeakSDUBandwidthDuration() {
        bitField0_ = (bitField0_ & ~0x00000020);
        peakSDUBandwidthDuration_ = 0;
        onChanged();
        return this;
      }
      
      // optional double undetectedBitErrorRate = 7;
      private double undetectedBitErrorRate_ ;
      public boolean hasUndetectedBitErrorRate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getUndetectedBitErrorRate() {
        return undetectedBitErrorRate_;
      }
      public Builder setUndetectedBitErrorRate(double value) {
        bitField0_ |= 0x00000040;
        undetectedBitErrorRate_ = value;
        onChanged();
        return this;
      }
      public Builder clearUndetectedBitErrorRate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        undetectedBitErrorRate_ = 0D;
        onChanged();
        return this;
      }
      
      // optional bool partialDelivery = 8;
      private boolean partialDelivery_ ;
      public boolean hasPartialDelivery() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public boolean getPartialDelivery() {
        return partialDelivery_;
      }
      public Builder setPartialDelivery(boolean value) {
        bitField0_ |= 0x00000080;
        partialDelivery_ = value;
        onChanged();
        return this;
      }
      public Builder clearPartialDelivery() {
        bitField0_ = (bitField0_ & ~0x00000080);
        partialDelivery_ = false;
        onChanged();
        return this;
      }
      
      // optional bool order = 9;
      private boolean order_ ;
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public boolean getOrder() {
        return order_;
      }
      public Builder setOrder(boolean value) {
        bitField0_ |= 0x00000100;
        order_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000100);
        order_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 maxAllowableGapSdu = 10;
      private int maxAllowableGapSdu_ ;
      public boolean hasMaxAllowableGapSdu() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getMaxAllowableGapSdu() {
        return maxAllowableGapSdu_;
      }
      public Builder setMaxAllowableGapSdu(int value) {
        bitField0_ |= 0x00000200;
        maxAllowableGapSdu_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxAllowableGapSdu() {
        bitField0_ = (bitField0_ & ~0x00000200);
        maxAllowableGapSdu_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 delay = 11;
      private int delay_ ;
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getDelay() {
        return delay_;
      }
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000400;
        delay_ = value;
        onChanged();
        return this;
      }
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000400);
        delay_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 jitter = 12;
      private int jitter_ ;
      public boolean hasJitter() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getJitter() {
        return jitter_;
      }
      public Builder setJitter(int value) {
        bitField0_ |= 0x00000800;
        jitter_ = value;
        onChanged();
        return this;
      }
      public Builder clearJitter() {
        bitField0_ = (bitField0_ & ~0x00000800);
        jitter_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .rina.messages.property_t extraParameters = 13;
      private java.util.List<rina.object.gpb.PropertyMessage_t.property_t> extraParameters_ =
        java.util.Collections.emptyList();
      private void ensureExtraParametersIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          extraParameters_ = new java.util.ArrayList<rina.object.gpb.PropertyMessage_t.property_t>(extraParameters_);
          bitField0_ |= 0x00001000;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.PropertyMessage_t.property_t, rina.object.gpb.PropertyMessage_t.property_t.Builder, rina.object.gpb.PropertyMessage_t.property_tOrBuilder> extraParametersBuilder_;
      
      public java.util.List<rina.object.gpb.PropertyMessage_t.property_t> getExtraParametersList() {
        if (extraParametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extraParameters_);
        } else {
          return extraParametersBuilder_.getMessageList();
        }
      }
      public int getExtraParametersCount() {
        if (extraParametersBuilder_ == null) {
          return extraParameters_.size();
        } else {
          return extraParametersBuilder_.getCount();
        }
      }
      public rina.object.gpb.PropertyMessage_t.property_t getExtraParameters(int index) {
        if (extraParametersBuilder_ == null) {
          return extraParameters_.get(index);
        } else {
          return extraParametersBuilder_.getMessage(index);
        }
      }
      public Builder setExtraParameters(
          int index, rina.object.gpb.PropertyMessage_t.property_t value) {
        if (extraParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraParametersIsMutable();
          extraParameters_.set(index, value);
          onChanged();
        } else {
          extraParametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExtraParameters(
          int index, rina.object.gpb.PropertyMessage_t.property_t.Builder builderForValue) {
        if (extraParametersBuilder_ == null) {
          ensureExtraParametersIsMutable();
          extraParameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          extraParametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExtraParameters(rina.object.gpb.PropertyMessage_t.property_t value) {
        if (extraParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraParametersIsMutable();
          extraParameters_.add(value);
          onChanged();
        } else {
          extraParametersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExtraParameters(
          int index, rina.object.gpb.PropertyMessage_t.property_t value) {
        if (extraParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraParametersIsMutable();
          extraParameters_.add(index, value);
          onChanged();
        } else {
          extraParametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExtraParameters(
          rina.object.gpb.PropertyMessage_t.property_t.Builder builderForValue) {
        if (extraParametersBuilder_ == null) {
          ensureExtraParametersIsMutable();
          extraParameters_.add(builderForValue.build());
          onChanged();
        } else {
          extraParametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExtraParameters(
          int index, rina.object.gpb.PropertyMessage_t.property_t.Builder builderForValue) {
        if (extraParametersBuilder_ == null) {
          ensureExtraParametersIsMutable();
          extraParameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          extraParametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExtraParameters(
          java.lang.Iterable<? extends rina.object.gpb.PropertyMessage_t.property_t> values) {
        if (extraParametersBuilder_ == null) {
          ensureExtraParametersIsMutable();
          super.addAll(values, extraParameters_);
          onChanged();
        } else {
          extraParametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExtraParameters() {
        if (extraParametersBuilder_ == null) {
          extraParameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00001000);
          onChanged();
        } else {
          extraParametersBuilder_.clear();
        }
        return this;
      }
      public Builder removeExtraParameters(int index) {
        if (extraParametersBuilder_ == null) {
          ensureExtraParametersIsMutable();
          extraParameters_.remove(index);
          onChanged();
        } else {
          extraParametersBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.PropertyMessage_t.property_t.Builder getExtraParametersBuilder(
          int index) {
        return getExtraParametersFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.PropertyMessage_t.property_tOrBuilder getExtraParametersOrBuilder(
          int index) {
        if (extraParametersBuilder_ == null) {
          return extraParameters_.get(index);  } else {
          return extraParametersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.PropertyMessage_t.property_tOrBuilder> 
           getExtraParametersOrBuilderList() {
        if (extraParametersBuilder_ != null) {
          return extraParametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extraParameters_);
        }
      }
      public rina.object.gpb.PropertyMessage_t.property_t.Builder addExtraParametersBuilder() {
        return getExtraParametersFieldBuilder().addBuilder(
            rina.object.gpb.PropertyMessage_t.property_t.getDefaultInstance());
      }
      public rina.object.gpb.PropertyMessage_t.property_t.Builder addExtraParametersBuilder(
          int index) {
        return getExtraParametersFieldBuilder().addBuilder(
            index, rina.object.gpb.PropertyMessage_t.property_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.PropertyMessage_t.property_t.Builder> 
           getExtraParametersBuilderList() {
        return getExtraParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.PropertyMessage_t.property_t, rina.object.gpb.PropertyMessage_t.property_t.Builder, rina.object.gpb.PropertyMessage_t.property_tOrBuilder> 
          getExtraParametersFieldBuilder() {
        if (extraParametersBuilder_ == null) {
          extraParametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.PropertyMessage_t.property_t, rina.object.gpb.PropertyMessage_t.property_t.Builder, rina.object.gpb.PropertyMessage_t.property_tOrBuilder>(
                  extraParameters_,
                  ((bitField0_ & 0x00001000) == 0x00001000),
                  getParentForChildren(),
                  isClean());
          extraParameters_ = null;
        }
        return extraParametersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.qosSpecification_t)
    }
    
    static {
      defaultInstance = new qosSpecification_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.qosSpecification_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_qosSpecification_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_qosSpecification_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026QoSSpecification.proto\022\rrina.messages\032" +
      "\025PropertyMessage.proto\"\340\002\n\022qosSpecificat" +
      "ion_t\022\014\n\004name\030\001 \001(\t\022\r\n\005qosid\030\002 \001(\r\022\030\n\020av" +
      "erageBandwidth\030\003 \001(\004\022\033\n\023averageSDUBandwi" +
      "dth\030\004 \001(\004\022\035\n\025peakBandwidthDuration\030\005 \001(\r" +
      "\022 \n\030peakSDUBandwidthDuration\030\006 \001(\r\022\036\n\026un" +
      "detectedBitErrorRate\030\007 \001(\001\022\027\n\017partialDel" +
      "ivery\030\010 \001(\010\022\r\n\005order\030\t \001(\010\022\032\n\022maxAllowab" +
      "leGapSdu\030\n \001(\005\022\r\n\005delay\030\013 \001(\r\022\016\n\006jitter\030" +
      "\014 \001(\r\0222\n\017extraParameters\030\r \003(\0132\031.rina.me",
      "ssages.property_t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_qosSpecification_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_qosSpecification_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_qosSpecification_t_descriptor,
              new java.lang.String[] { "Name", "Qosid", "AverageBandwidth", "AverageSDUBandwidth", "PeakBandwidthDuration", "PeakSDUBandwidthDuration", "UndetectedBitErrorRate", "PartialDelivery", "Order", "MaxAllowableGapSdu", "Delay", "Jitter", "ExtraParameters", },
              rina.object.gpb.QoSSpecification_t.qosSpecification_t.class,
              rina.object.gpb.QoSSpecification_t.qosSpecification_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.object.gpb.PropertyMessage_t.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
