/**
 * @copyright 2013 Computer Science Department, Recursive InterNetworking Architecture (RINA) laboratory, Boston University. 
 * All rights reserved. Permission to use, copy, modify, and distribute this software and its documentation
 * for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all 
 * copies and that both the copyright notice and this permission notice appear in supporting documentation. 
 * The RINA laboratory of the Computer Science Department at Boston University makes no 
 * representations about the suitability of this software for any purpose. 
 * It is provided "as is" without express or implied warranty. 
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: whatevercast.proto

package rina.object.gpb;

public final class Whatevercast_t {
  private Whatevercast_t() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface whatevercastNames_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .rina.messages.whatevercastName_t whatevercastName = 1;
    java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t> 
        getWhatevercastNameList();
    rina.object.gpb.Whatevercast_t.whatevercastName_t getWhatevercastName(int index);
    int getWhatevercastNameCount();
    java.util.List<? extends rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder> 
        getWhatevercastNameOrBuilderList();
    rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder getWhatevercastNameOrBuilder(
        int index);
  }
  public static final class whatevercastNames_t extends
      com.google.protobuf.GeneratedMessage
      implements whatevercastNames_tOrBuilder {
    // Use whatevercastNames_t.newBuilder() to construct.
    private whatevercastNames_t(Builder builder) {
      super(builder);
    }
    private whatevercastNames_t(boolean noInit) {}
    
    private static final whatevercastNames_t defaultInstance;
    public static whatevercastNames_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public whatevercastNames_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastNames_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastNames_t_fieldAccessorTable;
    }
    
    // repeated .rina.messages.whatevercastName_t whatevercastName = 1;
    public static final int WHATEVERCASTNAME_FIELD_NUMBER = 1;
    private java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t> whatevercastName_;
    public java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t> getWhatevercastNameList() {
      return whatevercastName_;
    }
    public java.util.List<? extends rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder> 
        getWhatevercastNameOrBuilderList() {
      return whatevercastName_;
    }
    public int getWhatevercastNameCount() {
      return whatevercastName_.size();
    }
    public rina.object.gpb.Whatevercast_t.whatevercastName_t getWhatevercastName(int index) {
      return whatevercastName_.get(index);
    }
    public rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder getWhatevercastNameOrBuilder(
        int index) {
      return whatevercastName_.get(index);
    }
    
    private void initFields() {
      whatevercastName_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getWhatevercastNameCount(); i++) {
        if (!getWhatevercastName(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < whatevercastName_.size(); i++) {
        output.writeMessage(1, whatevercastName_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < whatevercastName_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, whatevercastName_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastNames_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.Whatevercast_t.whatevercastNames_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.Whatevercast_t.whatevercastNames_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastNames_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastNames_t_fieldAccessorTable;
      }
      
      // Construct using rina.messages.Whatevercast.whatevercastNames_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWhatevercastNameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (whatevercastNameBuilder_ == null) {
          whatevercastName_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          whatevercastNameBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.Whatevercast_t.whatevercastNames_t.getDescriptor();
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastNames_t getDefaultInstanceForType() {
        return rina.object.gpb.Whatevercast_t.whatevercastNames_t.getDefaultInstance();
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastNames_t build() {
        rina.object.gpb.Whatevercast_t.whatevercastNames_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.Whatevercast_t.whatevercastNames_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.Whatevercast_t.whatevercastNames_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastNames_t buildPartial() {
        rina.object.gpb.Whatevercast_t.whatevercastNames_t result = new rina.object.gpb.Whatevercast_t.whatevercastNames_t(this);
        int from_bitField0_ = bitField0_;
        if (whatevercastNameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            whatevercastName_ = java.util.Collections.unmodifiableList(whatevercastName_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.whatevercastName_ = whatevercastName_;
        } else {
          result.whatevercastName_ = whatevercastNameBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.Whatevercast_t.whatevercastNames_t) {
          return mergeFrom((rina.object.gpb.Whatevercast_t.whatevercastNames_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.Whatevercast_t.whatevercastNames_t other) {
        if (other == rina.object.gpb.Whatevercast_t.whatevercastNames_t.getDefaultInstance()) return this;
        if (whatevercastNameBuilder_ == null) {
          if (!other.whatevercastName_.isEmpty()) {
            if (whatevercastName_.isEmpty()) {
              whatevercastName_ = other.whatevercastName_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWhatevercastNameIsMutable();
              whatevercastName_.addAll(other.whatevercastName_);
            }
            onChanged();
          }
        } else {
          if (!other.whatevercastName_.isEmpty()) {
            if (whatevercastNameBuilder_.isEmpty()) {
              whatevercastNameBuilder_.dispose();
              whatevercastNameBuilder_ = null;
              whatevercastName_ = other.whatevercastName_;
              bitField0_ = (bitField0_ & ~0x00000001);
              whatevercastNameBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWhatevercastNameFieldBuilder() : null;
            } else {
              whatevercastNameBuilder_.addAllMessages(other.whatevercastName_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getWhatevercastNameCount(); i++) {
          if (!getWhatevercastName(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder subBuilder = rina.object.gpb.Whatevercast_t.whatevercastName_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addWhatevercastName(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .rina.messages.whatevercastName_t whatevercastName = 1;
      private java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t> whatevercastName_ =
        java.util.Collections.emptyList();
      private void ensureWhatevercastNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          whatevercastName_ = new java.util.ArrayList<rina.object.gpb.Whatevercast_t.whatevercastName_t>(whatevercastName_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.Whatevercast_t.whatevercastName_t, rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder, rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder> whatevercastNameBuilder_;
      
      public java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t> getWhatevercastNameList() {
        if (whatevercastNameBuilder_ == null) {
          return java.util.Collections.unmodifiableList(whatevercastName_);
        } else {
          return whatevercastNameBuilder_.getMessageList();
        }
      }
      public int getWhatevercastNameCount() {
        if (whatevercastNameBuilder_ == null) {
          return whatevercastName_.size();
        } else {
          return whatevercastNameBuilder_.getCount();
        }
      }
      public rina.object.gpb.Whatevercast_t.whatevercastName_t getWhatevercastName(int index) {
        if (whatevercastNameBuilder_ == null) {
          return whatevercastName_.get(index);
        } else {
          return whatevercastNameBuilder_.getMessage(index);
        }
      }
      public Builder setWhatevercastName(
          int index, rina.object.gpb.Whatevercast_t.whatevercastName_t value) {
        if (whatevercastNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWhatevercastNameIsMutable();
          whatevercastName_.set(index, value);
          onChanged();
        } else {
          whatevercastNameBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setWhatevercastName(
          int index, rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder builderForValue) {
        if (whatevercastNameBuilder_ == null) {
          ensureWhatevercastNameIsMutable();
          whatevercastName_.set(index, builderForValue.build());
          onChanged();
        } else {
          whatevercastNameBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addWhatevercastName(rina.object.gpb.Whatevercast_t.whatevercastName_t value) {
        if (whatevercastNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWhatevercastNameIsMutable();
          whatevercastName_.add(value);
          onChanged();
        } else {
          whatevercastNameBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addWhatevercastName(
          int index, rina.object.gpb.Whatevercast_t.whatevercastName_t value) {
        if (whatevercastNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWhatevercastNameIsMutable();
          whatevercastName_.add(index, value);
          onChanged();
        } else {
          whatevercastNameBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addWhatevercastName(
          rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder builderForValue) {
        if (whatevercastNameBuilder_ == null) {
          ensureWhatevercastNameIsMutable();
          whatevercastName_.add(builderForValue.build());
          onChanged();
        } else {
          whatevercastNameBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addWhatevercastName(
          int index, rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder builderForValue) {
        if (whatevercastNameBuilder_ == null) {
          ensureWhatevercastNameIsMutable();
          whatevercastName_.add(index, builderForValue.build());
          onChanged();
        } else {
          whatevercastNameBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllWhatevercastName(
          java.lang.Iterable<? extends rina.object.gpb.Whatevercast_t.whatevercastName_t> values) {
        if (whatevercastNameBuilder_ == null) {
          ensureWhatevercastNameIsMutable();
          super.addAll(values, whatevercastName_);
          onChanged();
        } else {
          whatevercastNameBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearWhatevercastName() {
        if (whatevercastNameBuilder_ == null) {
          whatevercastName_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          whatevercastNameBuilder_.clear();
        }
        return this;
      }
      public Builder removeWhatevercastName(int index) {
        if (whatevercastNameBuilder_ == null) {
          ensureWhatevercastNameIsMutable();
          whatevercastName_.remove(index);
          onChanged();
        } else {
          whatevercastNameBuilder_.remove(index);
        }
        return this;
      }
      public rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder getWhatevercastNameBuilder(
          int index) {
        return getWhatevercastNameFieldBuilder().getBuilder(index);
      }
      public rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder getWhatevercastNameOrBuilder(
          int index) {
        if (whatevercastNameBuilder_ == null) {
          return whatevercastName_.get(index);  } else {
          return whatevercastNameBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder> 
           getWhatevercastNameOrBuilderList() {
        if (whatevercastNameBuilder_ != null) {
          return whatevercastNameBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(whatevercastName_);
        }
      }
      public rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder addWhatevercastNameBuilder() {
        return getWhatevercastNameFieldBuilder().addBuilder(
            rina.object.gpb.Whatevercast_t.whatevercastName_t.getDefaultInstance());
      }
      public rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder addWhatevercastNameBuilder(
          int index) {
        return getWhatevercastNameFieldBuilder().addBuilder(
            index, rina.object.gpb.Whatevercast_t.whatevercastName_t.getDefaultInstance());
      }
      public java.util.List<rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder> 
           getWhatevercastNameBuilderList() {
        return getWhatevercastNameFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          rina.object.gpb.Whatevercast_t.whatevercastName_t, rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder, rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder> 
          getWhatevercastNameFieldBuilder() {
        if (whatevercastNameBuilder_ == null) {
          whatevercastNameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              rina.object.gpb.Whatevercast_t.whatevercastName_t, rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder, rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder>(
                  whatevercastName_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          whatevercastName_ = null;
        }
        return whatevercastNameBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.whatevercastNames_t)
    }
    
    static {
      defaultInstance = new whatevercastNames_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.whatevercastNames_t)
  }
  
  public interface whatevercastName_tOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string rule = 2;
    boolean hasRule();
    String getRule();
    
    // repeated bytes setMembers = 3;
    java.util.List<com.google.protobuf.ByteString> getSetMembersList();
    int getSetMembersCount();
    com.google.protobuf.ByteString getSetMembers(int index);
  }
  public static final class whatevercastName_t extends
      com.google.protobuf.GeneratedMessage
      implements whatevercastName_tOrBuilder {
    // Use whatevercastName_t.newBuilder() to construct.
    private whatevercastName_t(Builder builder) {
      super(builder);
    }
    private whatevercastName_t(boolean noInit) {}
    
    private static final whatevercastName_t defaultInstance;
    public static whatevercastName_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public whatevercastName_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastName_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastName_t_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string rule = 2;
    public static final int RULE_FIELD_NUMBER = 2;
    private java.lang.Object rule_;
    public boolean hasRule() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRule() {
      java.lang.Object ref = rule_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rule_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRuleBytes() {
      java.lang.Object ref = rule_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated bytes setMembers = 3;
    public static final int SETMEMBERS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> setMembers_;
    public java.util.List<com.google.protobuf.ByteString>
        getSetMembersList() {
      return setMembers_;
    }
    public int getSetMembersCount() {
      return setMembers_.size();
    }
    public com.google.protobuf.ByteString getSetMembers(int index) {
      return setMembers_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      rule_ = "";
      setMembers_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRuleBytes());
      }
      for (int i = 0; i < setMembers_.size(); i++) {
        output.writeBytes(3, setMembers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRuleBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < setMembers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(setMembers_.get(i));
        }
        size += dataSize;
        size += 1 * getSetMembersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.object.gpb.Whatevercast_t.whatevercastName_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.object.gpb.Whatevercast_t.whatevercastName_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rina.object.gpb.Whatevercast_t.whatevercastName_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastName_t_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rina.object.gpb.Whatevercast_t.internal_static_rina_messages_whatevercastName_t_fieldAccessorTable;
      }
      
      // Construct using rina.messages.Whatevercast.whatevercastName_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        rule_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        setMembers_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.object.gpb.Whatevercast_t.whatevercastName_t.getDescriptor();
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastName_t getDefaultInstanceForType() {
        return rina.object.gpb.Whatevercast_t.whatevercastName_t.getDefaultInstance();
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastName_t build() {
        rina.object.gpb.Whatevercast_t.whatevercastName_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rina.object.gpb.Whatevercast_t.whatevercastName_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rina.object.gpb.Whatevercast_t.whatevercastName_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rina.object.gpb.Whatevercast_t.whatevercastName_t buildPartial() {
        rina.object.gpb.Whatevercast_t.whatevercastName_t result = new rina.object.gpb.Whatevercast_t.whatevercastName_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rule_ = rule_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          setMembers_ = java.util.Collections.unmodifiableList(setMembers_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.setMembers_ = setMembers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.object.gpb.Whatevercast_t.whatevercastName_t) {
          return mergeFrom((rina.object.gpb.Whatevercast_t.whatevercastName_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.object.gpb.Whatevercast_t.whatevercastName_t other) {
        if (other == rina.object.gpb.Whatevercast_t.whatevercastName_t.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasRule()) {
          setRule(other.getRule());
        }
        if (!other.setMembers_.isEmpty()) {
          if (setMembers_.isEmpty()) {
            setMembers_ = other.setMembers_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSetMembersIsMutable();
            setMembers_.addAll(other.setMembers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasRule()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rule_ = input.readBytes();
              break;
            }
            case 26: {
              ensureSetMembersIsMutable();
              setMembers_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string rule = 2;
      private java.lang.Object rule_ = "";
      public boolean hasRule() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRule() {
        java.lang.Object ref = rule_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rule_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRule(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rule_ = value;
        onChanged();
        return this;
      }
      public Builder clearRule() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rule_ = getDefaultInstance().getRule();
        onChanged();
        return this;
      }
      void setRule(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        rule_ = value;
        onChanged();
      }
      
      // repeated bytes setMembers = 3;
      private java.util.List<com.google.protobuf.ByteString> setMembers_ = java.util.Collections.emptyList();;
      private void ensureSetMembersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          setMembers_ = new java.util.ArrayList<com.google.protobuf.ByteString>(setMembers_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getSetMembersList() {
        return java.util.Collections.unmodifiableList(setMembers_);
      }
      public int getSetMembersCount() {
        return setMembers_.size();
      }
      public com.google.protobuf.ByteString getSetMembers(int index) {
        return setMembers_.get(index);
      }
      public Builder setSetMembers(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSetMembersIsMutable();
        setMembers_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addSetMembers(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSetMembersIsMutable();
        setMembers_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllSetMembers(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSetMembersIsMutable();
        super.addAll(values, setMembers_);
        onChanged();
        return this;
      }
      public Builder clearSetMembers() {
        setMembers_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.whatevercastName_t)
    }
    
    static {
      defaultInstance = new whatevercastName_t(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.whatevercastName_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_whatevercastNames_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_whatevercastNames_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_whatevercastName_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_whatevercastName_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022whatevercast.proto\022\rrina.messages\"R\n\023w" +
      "hatevercastNames_t\022;\n\020whatevercastName\030\001" +
      " \003(\0132!.rina.messages.whatevercastName_t\"" +
      "D\n\022whatevercastName_t\022\014\n\004name\030\001 \002(\t\022\014\n\004r" +
      "ule\030\002 \002(\t\022\022\n\nsetMembers\030\003 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_whatevercastNames_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_whatevercastNames_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_whatevercastNames_t_descriptor,
              new java.lang.String[] { "WhatevercastName", },
              rina.object.gpb.Whatevercast_t.whatevercastNames_t.class,
              rina.object.gpb.Whatevercast_t.whatevercastNames_t.Builder.class);
          internal_static_rina_messages_whatevercastName_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_messages_whatevercastName_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_whatevercastName_t_descriptor,
              new java.lang.String[] { "Name", "Rule", "SetMembers", },
              rina.object.gpb.Whatevercast_t.whatevercastName_t.class,
              rina.object.gpb.Whatevercast_t.whatevercastName_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
